# Shared by test/test_mc_simulate_p1.jl and tools/true_parity_mc_simulate_receipt.jl: the Julia side of the
# Monte-Carlo moment twins for postfit/POSTFIT-SURFACE-simulate_unit_trait and postfit-policy/POST-SIMULATE-DEFAULT
# (maintainer ruling 2026-10-05, vault D-319, item N4). R values come from test/fixtures/mc_simulate_p1.toml
# (generated by test/fixtures/gen_mc_simulate_p1.R).
#
# MONTE-CARLO TOLERANCE RULE (stated 2026-10-05, before any run; the same text is in the R generator and in
# every receipt):
#   * Each engine produces B independent replicates (B is fixed in the fixture). From every replicate it computes
#     the same K moment statistics.
#   * For moment k, m_R, m_J are the replicate means and s_R, s_J the replicate standard deviations (n - 1
#     denominator) over B_k replicate values (B_k = B, or B / 2 for a statistic built from a pair of replicates).
#     tol_k = z * sqrt(s_R^2 / B_k + s_J^2 / B_k), z = quantile(Normal(), 1 - alpha / (2K)), alpha = 0.01:
#     a two-sided Bonferroni bound over the K moments (familywise alpha 0.01).
#   * The row passes when |m_R - m_J| <= tol_k for every k. No other tolerance is used, and the rule is not
#     loosened after a run.
#   * Discrimination control: an alternative that differs in the property the row names must FAIL the same rule
#     on at least one moment. unit_trait: Julia with psi_B doubled. simulate_default: R's
#     simulate(..., condition_on_RE = TRUE) (draws given the fitted latent modes) against the Julia default.
#   * Julia seeds: Random.Xoshiro(10_000 + b) for unit_trait replicate b, Xoshiro(20_000 + b) for its psi_B
#     control, one Xoshiro(30_000) stream for the B simulate_default data sets. R seeds are in the fixture.

using GLLVModels, Statistics, Random, LinearAlgebra
using Distributions: Normal, Poisson, quantile

mc_upper(S::AbstractMatrix) = [S[i, j] for j in axes(S, 2) for i in 1:j]   # R's S[upper.tri(S, diag = TRUE)]

mc_summary(M::AbstractMatrix) = (mean = vec(mean(M; dims = 1)), sd = vec(std(M; dims = 1)), n = size(M, 1))

mc_z(alpha, K) = quantile(Normal(), 1 - alpha / (2K))

"""(diff, tol) per moment under the rule; R and Julia means/sds and replicate counts."""
function mc_rule(r_mean, r_sd, r_n, j_mean, j_sd, j_n, z)
    length(r_mean) == length(j_mean) == length(r_sd) == length(j_sd) || error("moment length mismatch")
    diff = abs.(r_mean .- j_mean)
    tol = z .* sqrt.(r_sd .^ 2 ./ r_n .+ j_sd .^ 2 ./ j_n)
    return diff, tol
end

# ---- unit_trait: trait means (T), pooled within-unit covariance (divisor U(O-1)), covariance of unit means.
function mc_ut_moments(Y::AbstractMatrix, U::Integer, O::Integer)
    T = size(Y, 1)
    unit = repeat(1:U; inner = O)
    ybar = hcat([vec(mean(Y[:, unit .== u]; dims = 2)) for u in 1:U]...)   # T x U
    R = Y .- ybar[:, unit]
    return vcat(vec(mean(Y; dims = 2)), mc_upper(R * R' ./ (U * (O - 1))), mc_upper(cov(permutedims(ybar))))
end

function mc_unit_trait_julia(fx::AbstractDict, B::Integer; psi_scale::Real = 1.0, seed0::Integer = 10_000)
    T, U, O = fx["n_traits"], fx["n_units"], fx["n_obs_per_unit"]
    ΛB = reshape(Float64.(fx["Lambda_B"]), T, 2)
    ΛW = reshape(Float64.(fx["Lambda_W"]), T, 1)
    rows = map(1:B) do b
        sim = GLLVModels.simulate_unit_trait(Random.Xoshiro(seed0 + b); n_units = U, n_obs_per_unit = O,
                                             n_traits = T, K_B = 2, K_W = 1, alpha = Float64.(fx["alpha_t"]),
                                             Lambda_B = ΛB, Lambda_W = ΛW,
                                             psi_B = psi_scale .* Float64.(fx["psi_B"]), psi_W = Float64.(fx["psi_W"]),
                                             sigma2_eps = Float64(fx["sigma2_eps"]))
        mc_ut_moments(sim.Y, U, O)
    end
    return mc_summary(permutedims(hcat(rows...)))
end

# ---- simulate_default: per data set trait means (p) and covariance across units (divisor n - 1); per pair of
# data sets (2j - 1, 2j) the within-cell variance mean_s (Y1[t, s] - Y2[t, s])^2 / 2 per trait.
function mc_sd_moments(sims::AbstractVector{<:AbstractMatrix})
    m1 = permutedims(hcat([vcat(vec(mean(Y; dims = 2)), mc_upper(cov(permutedims(Float64.(Y))))) for Y in sims]...))
    m2 = permutedims(hcat([vec(mean((Float64.(sims[j]) .- Float64.(sims[j + 1])) .^ 2; dims = 2)) ./ 2
                           for j in 1:2:length(sims)]...))
    return (m1 = mc_summary(m1), m2 = mc_summary(m2))
end

function mc_simulate_default_julia(fx::AbstractDict, B::Integer)
    p, n = fx["p"], fx["n"]
    Y = reshape(Int.(fx["y"]), p, n)
    fit = GLLVModels.fit_gllvm(Y; family = Poisson(), K = 1)
    rng = Random.Xoshiro(30_000)
    sims = [GLLVModels.simulate(fit, n; rng = rng) for _ in 1:B]
    return fit, mc_sd_moments(sims)
end
