using Test
using GLLVModels

# --- Deterministic Julia-suite sharding (GLLVM_TEST_SHARD="k/N") -----------
# Splits the `include("test_*.jl")` calls below across N shards by file
# position: shard k (1-based) gets file i when (i - 1) % N == k - 1. Unset
# (default) runs every file — unchanged behaviour. Pure-logic helpers live in
# shard_util.jl and are exercised standalone in test_shard_selection.jl.
include("shard_util.jl")

_shard_spec = get(ENV, "GLLVM_TEST_SHARD", "")
_SHARD = isempty(_shard_spec) ? nothing : _parse_shard_spec(_shard_spec)

_shard_pos = Ref(0)
function _shard_include(path::AbstractString)
    _shard_pos[] += 1
    if _SHARD === nothing || (_shard_pos[] - 1) % _SHARD[2] == _SHARD[1] - 1
        include(path)
    end
end

# test_quality.jl (Aqua + JET) measured standalone at ~35s combined (2026-09)
# — far cheaper than the suite split across the files below, so it is not
# worth spreading across shards: it runs once, in shard 1 only (or always
# when unsharded), and is deliberately NOT behind `_shard_include` above.
_RUN_QUALITY = _SHARD === nothing || _SHARD[1] == 1

# File count for the header below: every `_shard_include("` call literally
# present in this file's own source — the same ordered list `_shard_include`
# walks at runtime — so the count can never drift from the include list as
# files are added or removed. Count only the INDENTED call sites: the bare
# literal also matches this very expression, a silent off-by-one in the header
# (harmless to selection, which uses the runtime `_shard_pos` counter, but
# wrong in the log). Carried over from PR #278.
_n_test_files = count("\n    _shard_include(\"", read(@__FILE__, String))
_n_selected = _SHARD === nothing ? _n_test_files :
    length(_shard_indices(_n_test_files, _SHARD[1], _SHARD[2]))
_n_reported = _n_selected + (_RUN_QUALITY ? 1 : 0)

println(_SHARD === nothing ?
    "GLLVModels tests: all files ($_n_reported files)" :
    "GLLVModels tests: shard $(_SHARD[1])/$(_SHARD[2]) — $_n_reported files")

# All suites run under one outer testset so that a failure in any included file
# does not abort the run before later files execute: included `@testset`s nest
# (Test uses dynamic scoping), accumulate, and only this root throws at the end —
# so one CI run reports every failure across all files, not just the first.
@testset "GLLVModels.jl" begin
    @testset "smoke" begin
        @test 1 + 1 == 2
        @test GLLVModels.GLLVM === GLLVModels
    end

    _shard_include("test_package_rename_alias.jl")
    _shard_include("test_shard_selection.jl")
    _shard_include("test_likelihood.jl")
    _shard_include("test_packing.jl")
    _shard_include("test_none_dep.jl")
    _shard_include("test_phylo_dep.jl")
    _shard_include("test_animal_dep.jl")
    _shard_include("test_animal_latent.jl")
    _shard_include("test_spatial_dep.jl")
    _shard_include("test_kernel_indep.jl")
    _shard_include("test_kernel_dep.jl")
    _shard_include("test_kernel_latent.jl")
    _shard_include("test_fit.jl")
    _shard_include("test_fixed_effects.jl")
    _shard_include("test_reml.jl")
    _shard_include("test_lv_predictor.jl")
    _shard_include("test_W_and_diag.jl")
    _shard_include("test_phy.jl")
    _shard_include("test_signed_sigma_phy.jl")
    _shard_include("test_sparse_phy.jl")
    _shard_include("test_phylo_precision.jl")
    _shard_include("test_precision_multivariate.jl")
    _shard_include("test_destination_b_reference.jl")
    _shard_include("test_destination_b_kernel_crosscheck.jl")
    _shard_include("test_destination_b_grouping_invariance.jl")
    _shard_include("test_destination_b_grouping_interval_matrix.jl")
    _shard_include("test_grouped_profile_foundation.jl")
    _shard_include("test_grouped_profile_refit.jl")
    _shard_include("test_grouped_profile_inversion.jl")
    _shard_include("test_grouped_profile_interval.jl")
    _shard_include("test_grouped_profile_dense_oracle.jl")
    _shard_include("test_grouped_profile_public.jl")
    _shard_include("test_joint_phylo_grouped_gaussian.jl")
    _shard_include("test_joint_covariance_identification.jl")
    _shard_include("test_joint_covariance_dense_gram.jl")
    _shard_include("test_joint_phylo_grouped_fit.jl")
    _shard_include("test_joint_phylo_grouped_alias_public.jl")
    _shard_include("test_joint_phylo_grouped_interior.jl")
    _shard_include("test_joint_phylo_grouped_postfit.jl")
    _shard_include("test_destination_b_precision_public.jl")
    _shard_include("test_marginal_target_intervals.jl")
    _shard_include("test_ppca_init.jl")
    _shard_include("test_em_fa.jl")
    _shard_include("test_lowrank_cholesky.jl")
    _shard_include("test_confint.jl")
    _shard_include("test_confint_profile.jl")
    _shard_include("test_profile_rootfind.jl")
    _shard_include("test_confint_bootstrap.jl")
    _shard_include("test_confint_derived.jl")
    _shard_include("test_confint_derived_wald.jl")
    _shard_include("test_profile_derived_fix.jl")
    _shard_include("test_takahashi_selinv.jl")
    _shard_include("test_em_louis.jl")
    _shard_include("test_em_sparse_estep_default.jl")
    _shard_include("test_node_gradient.jl")
    _shard_include("test_fit_phylo.jl")
    _shard_include("test_families.jl")
    _shard_include("test_binomial_laplace.jl")
    _shard_include("test_cloglog_likelihood.jl")
    _shard_include("test_aghq_grid.jl")
    _shard_include("test_aghq_adapt.jl")
    _shard_include("test_aghq_frozen.jl")
    _shard_include("test_aghq_outer.jl")
    _shard_include("test_aghq_multistart.jl")
    _shard_include("test_aghq_poisson.jl")
    _shard_include("test_aghq_public_poisson.jl")
    _shard_include("test_aghq_gaussian.jl")
    _shard_include("test_aghq_public_gaussian.jl")
    _shard_include("test_gaussian_empty_design.jl")
    _shard_include("test_profile_failure_bounds.jl")
    _shard_include("test_aghq_binomial.jl")
    _shard_include("test_aghq_public_binomial.jl")
    _shard_include("test_aghq_gate.jl")
    _shard_include("test_aghq_kd_bound.jl")
    _shard_include("test_poisson_laplace.jl")
    _shard_include("test_truncated_poisson.jl")
    _shard_include("test_censored_poisson.jl")
    _shard_include("test_truncated_nbinom2.jl")
    _shard_include("test_truncnb2_precision.jl")
    _shard_include("test_nb2_precision.jl")
    _shard_include("test_negbin_laplace.jl")
    _shard_include("test_beta_laplace.jl")
    _shard_include("test_ordinal_laplace.jl")
    _shard_include("test_gamma_laplace.jl")
    _shard_include("test_binomial_fit.jl")
    _shard_include("test_poisson_fit.jl")
    _shard_include("test_laplace_curvature_contract.jl")
    _shard_include("test_laplace_curvature_oracle.jl")
    _shard_include("test_laplace_dual_safety.jl")
    _shard_include("test_gamma_curvature_cross_kernel.jl")

    # Wired in 2026-08-25. These five were ORPHANED — present in test/, absent
    # from this file, and therefore never run in CI — while their sources
    # (src/phylo_*_xlv.jl) ARE shipped, included at src/GLLVModels.jl:103-107. That
    # is untested shipped code. All five pass; each was run individually first.
    #
    # test_phylo_gamma_xlv.jl is deliberately NOT wired in yet: its :123
    # assertion compares against a reference implementation inside the test file
    # that still computes the Fisher log-det, and updating that oracle should
    # not be done by whoever changed the code it judges.
    _shard_include("test_phylo_xlv.jl")
    _shard_include("test_phylo_beta_xlv.jl")

    # UN-WIRED 2026-08-25, having briefly been wired in. test_phylo_binomial_xlv,
    # test_phylo_nb_xlv, test_phylo_ordinal_xlv and test_sparse_phy_grad pass
    # locally but fail on CI, on DIFFERENT platform subsets each time:
    #
    #   macOS 1.12      ordinal (6), nb (2), sparse_phy_grad (1), binomial (1)
    #   Windows 1.12    nb (2), sparse_phy_grad (1), binomial (1)
    #   ubuntu 1.10     nb (2)
    #
    # Different platforms failing different subsets is instability, not a
    # deterministic bug. The failing assertions are the tell: `prof.pd_hessian`,
    # profile-CI endpoint status, and NaN/inverted CI bounds — all
    # optimiser-path and BLAS sensitive.
    #
    # This is very likely WHY they were orphaned. Wiring them in on the strength
    # of one local run, on one platform and one Julia version, was premature —
    # "passes locally" is not evidence that a numerically sensitive test is
    # stable. They need stabilising (fixed seeds per platform, or tolerance
    # analysis, or a `@test_broken`), which is its own slice and should be done
    # by someone looking at the numerics, not folded into a curvature PR.
    #
    #   include("test_phylo_binomial_xlv.jl")
    #   include("test_phylo_nb_xlv.jl")
    #   include("test_phylo_ordinal_xlv.jl")
    #   include("test_sparse_phy_grad.jl")


    # chibar2_pvalue / variance_lrt / profile_ci_variance are EXPORTED and had
    # zero tests. They return p-values and confidence intervals — the outputs
    # most likely to end up in a paper — so untested was the least acceptable
    # place for it. Every assertion is against an independently derived value.
    _shard_include("test_boundary_inference.jl")
    _shard_include("test_laplace_grad.jl")
    _shard_include("test_poisson_grad_perf.jl")
    _shard_include("test_grouped_laplace.jl")
    _shard_include("test_grouped_laplace_identity.jl")
    _shard_include("test_latte_kernel_identity.jl")
    _shard_include("test_grouped_analytic_grad.jl")
    _shard_include("test_laplace_grad_identity.jl")
    _shard_include("test_grouped_identification_diagnostics.jl")
    _shard_include("test_destination_b_joint_identification.jl")
    _shard_include("test_destination_b_joint_poisson.jl")
    _shard_include("test_destination_b_joint_other_families.jl")
    _shard_include("test_destination_b_joint_nb2_replication.jl")
    _shard_include("test_destination_b_quadrature.jl")
    _shard_include("test_masked_dispersion_grad.jl")
    _shard_include("test_laplace_alloc_equiv.jl")
    _shard_include("test_nb_fit.jl")
    _shard_include("test_nb1.jl")
    _shard_include("test_gp1_laplace.jl")
    _shard_include("test_grouped_dispersion.jl")
    _shard_include("test_grouped_dispersion_beta_gamma.jl")
    _shard_include("test_grouped_dispersion_tweedie_nb1.jl")
    _shard_include("test_nb_beta_x_identity.jl")
    _shard_include("test_gamma_x_identity.jl")
    _shard_include("test_nb1_x_identity.jl")
    _shard_include("test_betabinomial_x_identity.jl")
    _shard_include("test_ordinal_x_identity.jl")
    _shard_include("test_zip_x_identity.jl")
    _shard_include("test_zinb_x_identity.jl")
    _shard_include("test_beta_fit.jl")
    _shard_include("test_gamma_fit.jl")
    _shard_include("test_tweedie.jl")
    _shard_include("test_tweedie_engine_health.jl")
    _shard_include("test_tweedie_grouped_engine_health.jl")
    _shard_include("test_tweedie_power_contract.jl")
    _shard_include("test_exponential.jl")
    _shard_include("test_studentt.jl")
    _shard_include("test_studentt_input_validation.jl")
    _shard_include("test_studentt_disp_group.jl")
    _shard_include("test_studentt_core070.jl")
    _shard_include("test_studentt_boundary_honesty.jl")
    _shard_include("test_studentt_boundary.jl")
    _shard_include("test_studentt_normalizer_precision.jl")
    _shard_include("test_studentt_retained_precision.jl")
    _shard_include("test_lognormal.jl")
    _shard_include("test_multinomial.jl")
    _shard_include("test_zib_x_identity.jl")
    _shard_include("test_ordinal_fit.jl")
    _shard_include("test_ordinal_pertrait.jl")
    _shard_include("test_ordinal_probit.jl")
    _shard_include("test_fit_gllvm.jl")
    _shard_include("test_truncated_formula.jl")
    _shard_include("test_unified_api.jl")
    _shard_include("test_com_poisson.jl")
    _shard_include("test_gaussian_pervar.jl")
    _shard_include("test_gaussian_pervar_design.jl")
    _shard_include("test_gaussian_fixed_residual.jl")
    _shard_include("test_gaussian_pervar_fallback.jl")
    _shard_include("test_formula_pervar.jl")
    _shard_include("test_aicbic_newfits.jl")
    _shard_include("test_postfit.jl")
    _shard_include("test_statsapi.jl")
    _shard_include("test_postfit_zib_tweedie.jl")
    _shard_include("test_ordination.jl")
    _shard_include("test_model_selection.jl")
    _shard_include("test_structured_cov.jl")
    _shard_include("test_cross_kernel.jl")
    _shard_include("test_extract_gamma.jl")
    _shard_include("test_cross_kernel_fit.jl")
    _shard_include("test_source_covariance.jl")
    _shard_include("test_gaussian_sources.jl")
    _shard_include("test_grouped_gaussian.jl")
    _shard_include("test_grouped_fit.jl")
    _shard_include("test_destination_b_public.jl")
    _shard_include("test_destination_b_b1_unit_paired_fit.jl")
    _shard_include("test_destination_b_b1_unit_obs_paired_fit.jl")
    _shard_include("test_destination_b_b1_cluster_paired_fit.jl")
    _shard_include("test_destination_b_b1_cluster2_paired_fit.jl")
    _shard_include("test_destination_b_b1_joint_gaussian_paired_fit.jl")
    _shard_include("test_destination_b_b1_balanced_complete_crossed_design.jl")
    _shard_include("test_b1_fixed_coordinate_curvature_protocol.jl")
    _shard_include("test_b1_fixed_point_marginal_curvature_protocol.jl")
    _shard_include("test_precision_multivariate_fit.jl")
    _shard_include("test_precision_fit_admission.jl")
    _shard_include("test_precision_shared_residual.jl")
    _shard_include("test_destination_b_phylo_reference_checker.jl")
    _shard_include("test_destination_b_phylo_independent_receipt.jl")
    _shard_include("test_destination_b_pedigree_precision.jl")
    _shard_include("test_destination_b_tree_precision.jl")
    _shard_include("test_destination_b_tree_reference_checker.jl")
    _shard_include("test_destination_b_a4_s4_tree_julia_own_optimum.jl")
    _shard_include("test_destination_b_a4_s4_public_dense_bridge.jl")
    _shard_include("test_destination_b_a4_s4_public_r_formula_receipt.jl")
    _shard_include("test_destination_b_phylo_uncertainty.jl")
    _shard_include("test_destination_b_phylo_uncertainty_cli.jl")
    _shard_include("test_destination_b_dense_uncertainty.jl")
    _shard_include("test_destination_b_adapter_consumer.jl")
    _shard_include("test_destination_b_pedigree_reference_checker.jl")
    _shard_include("test_bridge_precision_shared_residual.jl")
    _shard_include("test_precision_objective_failures.jl")
    _shard_include("test_bridge_precision_multivariate.jl")
    _shard_include("test_grouped_nongaussian_fit.jl")
    _shard_include("test_destination_b_nongaussian_public.jl")
    _shard_include("test_destination_b_postfit.jl")
    _shard_include("test_grouped_nongaussian_postfit.jl")
    _shard_include("test_destination_b_fixed_effects.jl")
    _shard_include("test_gaussian_sources_fixed_residual.jl")
    _shard_include("test_source_fit_optimizer_health.jl")
    _shard_include("test_cross_objective_known_answer.jl")
    _shard_include("test_cross_objective_helpers.jl")
    _shard_include("test_gaussian_source_design.jl")
    _shard_include("test_formula_sources.jl")
    _shard_include("test_formula_structured_terms.jl")
    _shard_include("test_gaussian_source_bindings.jl")
    _shard_include("test_bridge_gradient_payload.jl")
    _shard_include("test_bridge_phylo_precision.jl")
    _shard_include("test_phylo_precision_animal.jl")
    _shard_include("test_bridge_sources.jl")
    _shard_include("test_coevolution_kronecker.jl")
    _shard_include("test_coevolution_blockna.jl")
    _shard_include("test_coevolution_glm.jl")
    _shard_include("test_spde.jl")
    _shard_include("test_spde_mesh.jl")
    _shard_include("test_spde_delaunay.jl")
    _shard_include("test_spde_fit.jl")
    _shard_include("test_spde_latent.jl")
    _shard_include("test_spde_latent_postfit.jl")
    _shard_include("test_phylo_glm.jl")
    _shard_include("test_phylo_poisson_xlv.jl")
    _shard_include("test_twopart_substrate.jl")
    _shard_include("test_twopart_alloc_equiv.jl")
    _shard_include("test_delta_fit.jl")
    _shard_include("test_delta_shared_predictor.jl")
    _shard_include("test_delta_disp_group.jl")
    _shard_include("test_delta_postfit.jl")
    _shard_include("test_hurdle_poisson.jl")
    _shard_include("test_hurdle_nb.jl")
    _shard_include("test_delta_gamma.jl")
    _shard_include("test_twopart_hessian_kwarg.jl")
    _shard_include("test_beta_hurdle.jl")
    _shard_include("test_beta_binomial.jl")
    _shard_include("test_zero_inflated.jl")
    _shard_include("test_missing_data.jl")
    _shard_include("test_missing_response.jl")
    _shard_include("test_missing_response_extra.jl")
    _shard_include("test_missing_predictor_fiml.jl")
    _shard_include("test_missing_predictor_phylo.jl")
    _shard_include("test_missing_predictor_z.jl")
    _shard_include("test_missing_predictor_poisson.jl")
    _shard_include("test_missing_predictor_dispersion.jl")
    _shard_include("test_missing_predictor_multi.jl")
    _shard_include("test_mi_fitter.jl")
    _shard_include("test_offset.jl")
    _shard_include("test_fd_hessian.jl")
    _shard_include("test_confint_family.jl")
    _shard_include("test_second_order_ordinal_pertrait_ci.jl")
    _shard_include("test_second_order_delta_followup.jl")
    _shard_include("test_second_order_s2_cloglog_ratified.jl")
    _shard_include("test_second_order_lognormal_ci.jl")
    _shard_include("test_second_order_truncpois_ci.jl")
    _shard_include("test_second_order_truncnb2_ci.jl")
    _shard_include("test_second_order_tweedie_grouped_ci.jl")
    _shard_include("test_second_order_multinomial_ci.jl")
    _shard_include("test_second_order_betabinomial_shared_ci.jl")
    _shard_include("test_second_order_studentt_ci.jl")
    _shard_include("test_diagnostics.jl")
    _shard_include("test_se_machinery.jl")
    _shard_include("test_nobs_pn_convention.jl")
    _shard_include("test_summary_table.jl")
    _shard_include("test_covariates.jl")
    _shard_include("test_formula_input.jl")
    _shard_include("test_formula.jl")
    _shard_include("test_simulate.jl")
    _shard_include("test_species_covariates.jl")
    _shard_include("test_fourthcorner.jl")
    _shard_include("test_row_effects.jl")
    _shard_include("test_row_random.jl")
    _shard_include("test_constrained_ordination.jl")
    _shard_include("test_rrr.jl")
    _shard_include("test_quadratic.jl")
    _shard_include("test_ordination_uncertainty.jl")
    _shard_include("test_structural_confint.jl")
    _shard_include("test_ordered_beta.jl")
    _shard_include("test_variational.jl")
    _shard_include("test_variational_binomial.jl")
    _shard_include("test_variational_negbin.jl")
    _shard_include("test_variational_gamma.jl")
    _shard_include("test_variational_beta.jl")
    _shard_include("test_variational_dgamma.jl")
    _shard_include("test_variational_exponential.jl")
    _shard_include("test_va_vs_laplace.jl")
    _shard_include("test_random_slopes.jl")
    _shard_include("test_twolevel.jl")
    _shard_include("test_random_slopes_poisson.jl")
    _shard_include("test_bridge_ci.jl")
    _shard_include("test_bridge_grouped_dispersion.jl")
    _shard_include("test_bridge_capabilities.jl")
    _shard_include("test_bridge_mixed.jl")
    _shard_include("test_bridge_x.jl")
    _shard_include("test_bridge_zib.jl")
    _shard_include("test_bridge_zip_nox.jl")
    _shard_include("test_bridge_lognormal.jl")
    _shard_include("test_bridge_truncated_poisson.jl")
    _shard_include("test_bridge_truncated_input.jl")
    _shard_include("test_bridge_lv_predictor.jl")
    _shard_include("test_lv_ci.jl")
    _shard_include("test_phylo_eta_realized.jl")
    _shard_include("test_bridge_missing_mask.jl")
    _shard_include("test_hessian_kwarg.jl")
    _shard_include("test_confint_hessian_consistency.jl")
    _shard_include("test_grouped_hessian_consistency.jl")
    _shard_include("test_saturation_health.jl")
    _shard_include("test_known_sentinel_defects.jl")
    _shard_include("test_curvature_census.jl")
    _shard_include("test_phylo_contrasts.jl")
    _shard_include("test_edge_incidence.jl")
    _shard_include("test_phylo_branch_re.jl")
    _shard_include("test_branch_re_marginal_fallback.jl")
    _shard_include("test_core070_receipts.jl")
    _shard_include("test_core070_interface_registry.jl")
    _shard_include("test_core070_shape_boundaries.jl")
    _shard_include("test_ordinal_link_input.jl")
    _shard_include("test_core070_link_boundaries.jl")
    _shard_include("test_parity_trial_inputs.jl")
    _shard_include("test_em_phylo.jl")
    _shard_include("test_sparse_phy_identities.jl")
    _shard_include("test_em_squarem.jl")
    _shard_include("test_em_squarem_safety.jl")
    _shard_include("test_relaxed_clock.jl")
    _shard_include("test_spatial_cov.jl")
    _shard_include("test_cv.jl")
    _RUN_QUALITY && include("test_quality.jl")
    _shard_include("test_loading_profile_stage0.jl")
    _shard_include("test_loading_profile_stage1_harness.jl")
    _shard_include("test_derived_ci_surfaces.jl")
    _shard_include("test_extractors.jl")
    _shard_include("test_postfit_tables.jl")
    _shard_include("test_destination_b_s4_public_phylo_dep_probe_harness.jl")
end
