# gllvm-parity-tag: P1
#
# Twin test for gllvmTMB's AIC.gllvmTMB_multi / BIC.gllvmTMB_multi /
# anova.gllvmTMB_multi / print.anova.gllvmTMB_multi (R/aghq-report.R, pin
# 9539352f66f2db2cc26b1c393e67212a359b60c9). See src/model_comparison.jl for
# why `update.gllvmTMB_multi` has no twin.
#
# Fixture: test/fixtures/gllvmtmb_anova_fixture.toml, generated by
# test/fixtures/generate_gllvmtmb_anova_fixture.R (as JSON, then converted
# exactly to TOML by test/fixtures/convert_gllvmtmb_anova_fixture_to_toml.jl so
# this file loads under `julia --project=.` with stdlibs only) from a real gllvmTMB fit at
# the P1 pin (three nested Gaussian long-format fits differing only in
# latent rank d = 1, 2, 3). Two twin layers:
#   1. DEFINITION twin: `GLLVModels._anova_core` and the aic/bic FORMULAS are
#      evaluated directly on R's recorded npar/loglik/nobs numbers, with no
#      Julia fitting involved — this isolates the arithmetic from any
#      possible fitting difference.
#   2. END-TO-END twin: GLLVModels.jl fits the fixture's own response matrix
#      with `fit_gaussian_gllvm(Y; X, K)` (explicit per-species-intercept X
#      — see src/model_comparison.jl for why plain `fit_gaussian_gllvm(Y; K)`
#      is NOT the same model as R's `y ~ 0 + trait + latent(...)` fixture),
#      then checks dof/loglikelihood/aic/bic/gllvm_anova against the fixture
#      at a looser tolerance (independent optimizers, same objective).

using GLLVModels, Test, TOML, SHA

const _FIXTURE_DIR  = joinpath(@__DIR__, "fixtures")
const _FIXTURE_PATH = joinpath(_FIXTURE_DIR, "gllvmtmb_anova_fixture.toml")
const _FIXTURE_SHA256 = "b06237b50c5a5f8a7fe916a04554fa8d2a2ea014c100c5b2cf61415b40227d78"

_sha(path) = bytes2hex(sha256(read(path)))

@testset "gllvm_anova / aic / bic — gllvmTMB P1 twin" begin

    @test isfile(_FIXTURE_PATH)
    @test _sha(_FIXTURE_PATH) == _FIXTURE_SHA256

    fx = TOML.parsefile(_FIXTURE_PATH)
    per_model = fx["per_model"]
    n_models = length(per_model)
    @test n_models == 3

    npar_r   = Int[m["npar"] for m in per_model]
    loglik_r = Float64[m["loglik"] for m in per_model]
    nobs_r   = Int[m["nobs"] for m in per_model]
    d_r      = Union{Missing,Int}[m["d"] for m in per_model]
    aic_r    = Float64[m["aic"] for m in per_model]
    bic_r    = Float64[m["bic"] for m in per_model]

    @testset "AIC/BIC formula twin (from R's recorded logLik/df/nobs)" begin
        for i in 1:n_models
            aic_formula = 2 * npar_r[i] - 2 * loglik_r[i]
            bic_formula = npar_r[i] * log(nobs_r[i]) - 2 * loglik_r[i]
            # This is the exact formula StatsAPI.aic/StatsAPI.bic use
            # (src/postfit.jl) — R's AIC.gllvmTMB_multi/BIC.gllvmTMB_multi
            # wrap stats::AIC/BIC (k = 2, attr(logLik, "df"), nobs(object)),
            # which is the identical textbook formula.
            @test aic_formula ≈ aic_r[i] atol=1e-6
            @test bic_formula ≈ bic_r[i] atol=1e-6
        end
    end

    p_r = Int(fx["meta"]["p_trait"])  # species/trait count; needed to verify a rank step's q

    @testset "_anova_core definition twin — test = :chibar" begin
        tab = GLLVModels._anova_core(npar_r, loglik_r, d_r, p_r; test = :chibar)
        ref = fx["anova_chibar"]
        @test tab.npar == npar_r
        @test tab.loglik ≈ loglik_r
        for i in 2:n_models
            @test tab.df[i] == ref["df"][i]
            @test tab.LRT[i] ≈ Float64(ref["LRT"][i]) atol=1e-6
            @test tab.pvalue[i] ≈ Float64(ref["pvalue"][i]) atol=1e-6
            # R labels a rank step "chibar (q=Q)"; Julia's method string
            # follows the identical convention.
            @test occursin("chibar", tab.test[i])
        end
    end

    @testset "_anova_core definition twin — test = :chisq" begin
        tab = GLLVModels._anova_core(npar_r, loglik_r, d_r, p_r; test = :chisq)
        ref = fx["anova_chisq"]
        for i in 2:n_models
            @test tab.LRT[i] ≈ Float64(ref["LRT"][i]) atol=1e-6
            @test tab.pvalue[i] ≈ Float64(ref["pvalue"][i]) atol=1e-6
            @test occursin("chisq", tab.test[i])
        end
    end

    @testset "_anova_core: test = :none reports no p-values (rank steps)" begin
        tab = GLLVModels._anova_core(npar_r, loglik_r, d_r, p_r; test = :none)
        for i in 2:n_models
            @test tab.test[i] == "none"
            @test tab.pvalue[i] === missing
            # LRT/df are still reported; only the p-value is withheld.
            @test tab.LRT[i] !== missing
        end
    end

    @testset "end-to-end: GLLVModels.jl fits of the fixture's own data" begin
        Yw = fx["Y_wide"]
        p = length(Yw)
        n = length(Yw[1])
        Y = Matrix{Float64}(undef, p, n)
        for i in 1:p, j in 1:n
            Y[i, j] = Yw[i][j]
        end

        # Per-species intercept design: X[t, s, k] = 1{t == k}, the same
        # `y ~ 0 + trait + ...` fixed-effect structure the R fixture used.
        # (Plain `fit_gaussian_gllvm(Y; K)` with no X is a ZERO-MEAN model —
        # see src/model_comparison.jl — and is not comparable to R's fit.)
        X = zeros(p, n, p)
        for t in 1:p, s in 1:n
            X[t, s, t] = 1.0
        end

        fits = [fit_gaussian_gllvm(Y; X = X, K = K) for K in 1:3]

        for i in 1:3
            @test dof(fits[i]) == npar_r[i]
            @test loglikelihood(fits[i]) ≈ loglik_r[i] atol=1e-4
            @test aic(fits[i]) ≈ aic_r[i] atol=1e-3
            @test bic(fits[i], nobs(fits[i], Y)) ≈ bic_r[i] atol=1e-3
            @test nobs(fits[i], Y) == nobs_r[i]
        end

        tab = gllvm_anova(fits...; test = :chibar)
        @test tab.npar == npar_r
        ref = fx["anova_chibar"]
        for i in 2:3
            @test tab.LRT[i] ≈ Float64(ref["LRT"][i]) atol=1e-2
            @test tab.pvalue[i] ≈ Float64(ref["pvalue"][i]) atol=1e-2
        end

        # print.anova.gllvmTMB_multi twin: Base.show(MIME"text/plain") must
        # not error, and should mention every model row.
        io = IOBuffer()
        show(io, MIME"text/plain"(), tab)
        printed = String(take!(io))
        @test occursin("Likelihood-ratio comparison", printed)
        for i in 1:3
            @test occursin("Model $i", printed)
        end
    end

    @testset "gllvm_anova argument validation (twin of R's refusals)" begin
        Y = randn(4, 20)
        fit1 = fit_gaussian_gllvm(Y; K = 1)

        # R: "anova needs at least two gllvmTMB_multi fits to compare"
        @test_throws ArgumentError gllvm_anova(fit1)

        # invalid `test` (twin of R's match.arg failure)
        fit2 = fit_gaussian_gllvm(Y; K = 2)
        @test_throws ArgumentError gllvm_anova(fit1, fit2; test = :bogus)

        # duplicate npar (twin of R's "same number of free parameters" refusal)
        fit1b = fit_gaussian_gllvm(Y; K = 1)
        @test_throws ArgumentError gllvm_anova(fit1, fit1b)

        # REML fit refused (twin of R's "requires ordinary ML fits" refusal)
        Xr = ones(4, 20, 1)
        reml_fit = fit_gaussian_reml(Y, Xr; K = 1)
        @test_throws ArgumentError gllvm_anova(fit1, reml_fit)
    end

    @testset "gllvm_anova refuses a compound step instead of mislabelling it a rank test" begin
        # Regression for the review finding on this PR: comparing a no-X fit
        # at K to an X-ADDED fit at K+1 changes TWO things at once (fixed
        # effects appear, and the rank increases by 1). Using the naive
        # Δnpar as q silently absorbed the X's parameters into q and reported
        # a spuriously significant clean rank test ("chibar (q=7)",
        # p ≈ 8.1e-14, on data with no such 7-df boundary effect). The fix
        # verifies q = p - d_prev structurally and refuses the step when the
        # observed Δnpar does not match it.
        Y = randn(4, 25)
        p, n = size(Y)
        X = zeros(p, n, p)
        for t in 1:p, s in 1:n
            X[t, s, t] = 1.0
        end
        fit_noX_K1 = fit_gaussian_gllvm(Y; K = 1)
        fit_X_K2   = fit_gaussian_gllvm(Y; X = X, K = 2)

        # dof: 5 (no X, K=1: 0 + 1 + 4) vs 12 (X, K=2: 4 + 1 + 7) — Δnpar = 7,
        # but the clean rank-only q at p=4, d_prev=1 is p - d_prev = 3.
        @test dof(fit_noX_K1) == 5
        @test dof(fit_X_K2) == 12

        tab = gllvm_anova(fit_noX_K1, fit_X_K2; test = :chibar)
        @test tab.test[2] == "refused"
        @test tab.pvalue[2] === missing
        @test tab.note[2] !== missing
        @test occursin("3", tab.note[2])  # names the expected q = p - d_prev = 3
    end

    @testset "gllvm_anova refuses fits of different concrete type / family" begin
        Yg = randn(4, 20)
        Yp = [rand(1:5) for _ in 1:4, _ in 1:20]
        fit_gauss = fit_gaussian_gllvm(Yg; K = 1)
        fit_pois  = fit_poisson_gllvm(Yp; K = 1)
        @test typeof(fit_gauss) !== typeof(fit_pois)
        @test_throws ArgumentError gllvm_anova(fit_gauss, fit_pois)
    end

    @testset "gllvm_anova refuses fits with a different species/trait count" begin
        Y4 = randn(4, 20)
        Y5 = randn(5, 20)
        fit_p4 = fit_gaussian_gllvm(Y4; K = 1)
        fit_p5 = fit_gaussian_gllvm(Y5; K = 1)
        @test size(GLLVModels._loadings(fit_p4), 1) != size(GLLVModels._loadings(fit_p5), 1)
        @test_throws ArgumentError gllvm_anova(fit_p4, fit_p5)
    end

    @testset "gllvm_anova: interior fixed-effect step (chi-square) end-to-end" begin
        # Same K (d unchanged), X added: a genuine interior fixed-effect
        # step, not a rank step — exercises the `is_fixed_step` branch that
        # the fixture-based tests above never touch (they only vary K).
        Y = randn(4, 30)
        p, n = size(Y)
        X = zeros(p, n, p)
        for t in 1:p, s in 1:n
            X[t, s, t] = 1.0
        end
        fit_noX = fit_gaussian_gllvm(Y; K = 1)
        fit_X   = fit_gaussian_gllvm(Y; X = X, K = 1)
        @test dof(fit_noX) < dof(fit_X)  # same K, so this must be a fixed step

        tab = gllvm_anova(fit_noX, fit_X; test = :chibar)
        @test tab.test[2] == "chisq"
        @test tab.pvalue[2] !== missing
        @test 0.0 <= tab.pvalue[2] <= 1.0
        @test occursin("Interior", tab.note[2])

        tab_none = gllvm_anova(fit_noX, fit_X; test = :none)
        @test tab_none.test[2] == "none"
        @test tab_none.pvalue[2] === missing
    end

    @testset "_anova_core: unclassified step gets a note, not a crash" begin
        # d unknown on both sides: cannot classify as rank or fixed.
        tab = GLLVModels._anova_core([5, 9], [-100.0, -90.0], [missing, missing])
        @test tab.test[2] == "refused"
        @test tab.pvalue[2] === missing
        @test tab.note[2] !== missing
    end
end
