# gllvm-parity-tag: P1
#
# Twin test for gllvmTMB's zero-inflated family exports zi_poisson(), zi_nbinom2(),
# zi_binomial() (family ids 17, 18, 19), pinned at gllvmTMB commit
# 9539352f66f2db2cc26b1c393e67212a359b60c9 ("P1" in the true-parity export ledger).
# No RCall: R's fitted values are read from test/fixtures/zi_p1.toml, generated by
# test/fixtures/gen_zi_p1.R against a real gllvmTMB install at that commit (see its
# header), and the same datasets are replayed here.
#
# Semantics (R/families.R, src/gllvmTMB.cpp fid 17/18/19, R/fit-multi.R): a true
# zero-inflation mixture with a per-trait, intercept-only structural-zero
# probability zi_t = logistic(logit_zi_t); count process active at every
# observation; eta = beta_t + Lambda_t' z; NB2 dispersion one phi per trait; binomial
# trials per observation, with single-trial-only traits refused; Laplace
# log-determinant from the observed curvature. Julia's own ZIPoisson / ZINegBin / ZIB
# routes differ (Fisher log-det weight; shared NB2 r; shared scalar N), so the R
# names use their own route (src/families/zi_twin.jl), checked here.
using Test
using GLLVModels
using TOML
using SHA
using Distributions
using ForwardDiff

const _ZI_FIXTURE_DIR = joinpath(@__DIR__, "fixtures")
const _ZI_TOML = joinpath(_ZI_FIXTURE_DIR, "zi_p1.toml")

# Parse the fixture's (site, trait, y[, trials]) CSV into p×n Int matrices. Written by
# hand (no CSV.jl test dependency); the format is what R's write.csv() emits here.
function _load_zi_csv(path::AbstractString, p::Integer, n::Integer)
    Y = zeros(Int, p, n); N = zeros(Int, p, n)
    lines = readlines(path)
    for line in lines[2:end]
        isempty(line) && continue
        parts = split(line, ",")
        s = parse(Int, parts[1]); t = parse(Int, parts[2])
        Y[t, s] = parse(Int, parts[3])
        length(parts) >= 4 && (N[t, s] = parse(Int, parts[4]))
    end
    return Y, N
end

# Independent (no latent) mixture log-density, written from R's hand-computed
# reference in tests/testthat/test-zi-families.R at P1.
function _zi_hand_loglik(fam, Y, β, logit_zi; phi = nothing, N = nothing)
    ll = 0.0
    for s in axes(Y, 2), t in axes(Y, 1)
        zi = 1 / (1 + exp(-logit_zi[t])); y = Y[t, s]
        d = fam isa ZiPoisson ? Poisson(exp(β[t])) :
            fam isa ZiNbinom2 ? NegativeBinomial(phi[t], phi[t] / (phi[t] + exp(β[t]))) :
                                Binomial(N[t, s], 1 / (1 + exp(-β[t])))
        ll += y == 0 ? log(zi + (1 - zi) * pdf(d, 0)) : log(1 - zi) + logpdf(d, y)
    end
    return ll
end

@testset "zi_* constructors and admission (gllvmTMB P1 semantics)" begin
    @test zi_poisson() isa ZiPoisson
    @test zi_nbinom2() isa ZiNbinom2
    @test zi_binomial() isa ZiBinomial
    # Not Julia's own markers under another name.
    @test !(zi_poisson() isa ZIPoisson)
    @test !(zi_nbinom2() isa ZINegBin)
    # R: "zi_poisson: only the log link is currently supported." (R/fit-multi.R)
    @test_throws ArgumentError zi_poisson(; link = IdentityLink())
    @test_throws ArgumentError zi_nbinom2(; link = IdentityLink())
    @test_throws ArgumentError zi_binomial(; link = ProbitLink())

    Y = [0 1 3 0 2 5 0 1 0 4 2 0
         2 0 0 1 4 0 3 0 1 0 0 2]
    @test_throws ArgumentError fit_gllvm(Y; family = zi_poisson(), K = 1, link = IdentityLink())
    @test_throws ArgumentError fit_gllvm(Y; family = zi_poisson(), K = 1, trials = 3)
    # `hessian` is accepted as a keyword and refused (this route is observed-only);
    # `:observed` is the route's own choice and is admitted.
    @test_throws ArgumentError fit_gllvm(Y; family = zi_poisson(), K = 1, hessian = :fisher)
    # Missing responses: R masks them per row; this route refuses them.
    Ym = Float64.(Y); Ym[1, 1] = NaN
    @test_throws ArgumentError fit_gllvm(Ym; family = zi_poisson(), K = 1)
    # ... and so does `missing` in a Union{Missing, Int} or Union{Missing, Float64}
    # matrix (the same refusal, not a MethodError).
    Ymi = Matrix{Union{Missing, Int}}(Y); Ymi[2, 3] = missing
    @test_throws ArgumentError fit_gllvm(Ymi; family = zi_poisson(), K = 1)
    @test_throws ArgumentError fit_zi_gllvm(Ymi; family = zi_nbinom2(), K = 1)
    Ymf = Matrix{Union{Missing, Float64}}(Float64.(Y)); Ymf[1, 2] = missing
    @test_throws ArgumentError fit_gllvm(Ymf; family = zi_binomial(), K = 1, trials = 6)
    err_m = try
        fit_gllvm(Ymf; family = zi_poisson(), K = 1); nothing
    catch e
        e
    end
    @test err_m isa ArgumentError && occursin("no missing", err_m.msg)
    @test_throws ArgumentError fit_gllvm(Float64.(Y) .+ 0.5; family = zi_poisson(), K = 1)
    @test_throws ArgumentError fit_gllvm(-Y; family = zi_nbinom2(), K = 1)
    # zi_binomial: trials required; y <= trials; single-trial traits refused (R names
    # binomial(); Julia names Binomial()).
    @test_throws ArgumentError fit_gllvm(min.(Y, 1); family = zi_binomial(), K = 1)
    @test_throws ArgumentError fit_gllvm(Y; family = zi_binomial(), K = 1, trials = 2)
    Nmix = fill(6, size(Y)); Nmix[2, :] .= 1
    err = try
        fit_gllvm(min.(Y, 1); family = zi_binomial(), K = 1, trials = Nmix)
        nothing
    catch e
        e
    end
    @test err isa ArgumentError
    @test occursin("single-trial", err.msg) && occursin("Trait(s) 2", err.msg) &&
          occursin("Binomial()", err.msg)
end

@testset "zi_marginal_loglik_laplace: exact at Λ = 0, observed curvature" begin
    Y = [0 1 3 0 2 5 0 1 0 4 2 0
         2 0 0 1 4 0 3 0 1 0 0 2]
    p, n = size(Y)
    β = [0.4, 0.1]; lz = [-1.0, -0.3]; phi = [1.7, 3.2]
    N = [6 5 7 4 8 6 5 7 6 8 5 6
         4 6 5 5 7 4 6 5 5 3 4 6]
    Λ0 = zeros(p, 1)
    # With Λ = 0 the site Laplace is exact (ẑ = 0, A = I): the value must be the
    # independent-mixture log-likelihood, the check R's own test runs at 1e-8.
    @test zi_marginal_loglik_laplace(zi_poisson(), Y, Λ0, β, lz) ≈
          _zi_hand_loglik(zi_poisson(), Y, β, lz) rtol = 1e-12
    @test zi_marginal_loglik_laplace(zi_nbinom2(), Y, Λ0, β, lz; phi = phi) ≈
          _zi_hand_loglik(zi_nbinom2(), Y, β, lz; phi = phi) rtol = 1e-12
    @test zi_marginal_loglik_laplace(zi_binomial(), Y, Λ0, β, lz; trials = N) ≈
          _zi_hand_loglik(zi_binomial(), Y, β, lz; N = N) rtol = 1e-12

    # The log-det weight is the observed curvature -d²logf/dη² (what TMB's AD
    # differentiates), checked against a central second difference of the density;
    # at y = 0 it differs from the Fisher weight Julia's own ZIPoisson route uses.
    G = GLLVModels
    c = G._ZiPoisCell(-0.7)
    logf(e) = G._tp_pieces(c, 0, c.logit_zi, e)[5]
    h = 1e-4; ηc = 0.9
    fd = -(logf(ηc + h) - 2logf(ηc) + logf(ηc - h)) / h^2
    obs = G._tp_observed_Wc(c, 0, ηc, NaN)
    @test obs ≈ fd rtol = 1e-6
    fisher = G._tp_pieces(G.ZIPoisson(), 0, c.logit_zi, ηc)[4]
    @test abs(obs - fisher) > 0.1
end

@testset "zi_* twins: gllvmTMB P1 (9539352f6) fixed datasets" begin
    if !isfile(_ZI_TOML)
        @warn "zi_* P1 fixture absent; twin gate NOT RUN" _ZI_TOML
        @test_skip false
    else
        fixture = TOML.parsefile(_ZI_TOML)
        p = Int(fixture["n_traits"])
        for (name, fam) in (("zi_poisson", zi_poisson()), ("zi_nbinom2", zi_nbinom2()),
                            ("zi_binomial", zi_binomial()))
            @testset "$name" begin
                fx = fixture[name]; r = fx["r_reference"]; rj = fx["r_at_julia"]
                data_path = joinpath(_ZI_FIXTURE_DIR, fx["data_file"])
                # Guard: the checked-in CSV must be byte-identical to what R fitted.
                @test bytes2hex(sha256(read(data_path))) == fx["data_sha256"]
                Y, N = _load_zi_csv(data_path, p, Int(fx["n_unit"]))
                trials = fam isa ZiBinomial ? N : nothing

                fit = fam isa ZiBinomial ? fit_gllvm(Y; family = fam, K = 1, trials = N) :
                                           fit_gllvm(Y; family = fam, K = 1)
                @test fit isa ZiFit
                @test fit.family === Symbol(name)
                @test fit.converged

                βR = Float64.(r["beta"]); ΛR = reshape(Float64.(r["Lambda_B"]), p, 1)
                lzR = Float64.(r["logit_zi"])
                phiR = haskey(r, "phi") ? Float64.(r["phi"]) : nothing
                llR = Float64(r["loglik"])

                # (1) Optimum vs optimum.
                d_opt = abs(fit.loglik - llR)
                # (2) Cross-objective, Julia's objective at R's optimum vs R's logLik
                #     (the likelihood identity, free of either optimiser's path).
                ll_j_at_R = zi_marginal_loglik_laplace(fam, Float64.(Y), ΛR, βR, lzR;
                                                       phi = phiR, trials = trials)
                d_cross_j = abs(ll_j_at_R - llR)
                # (3) Cross-objective the other way: R's TMB objective at Julia's
                #     optimum (recorded by gen_zi_p1.R phase 2) vs Julia's own value
                #     at that optimum (recorded alongside it).
                d_cross_r = abs(Float64(rj["r_objective_at_julia_optimum"]) -
                                Float64(rj["julia_loglik"]))
                # ... and this run reproduces the recorded Julia optimum.
                d_rerun = abs(fit.loglik - Float64(rj["julia_loglik"]))
                # (4) Parameters. Loadings are sign-identified only at K = 1, so the
                #     twin target is Λ Λ'.
                d_zi = maximum(abs.(fit.zi .- Float64.(r["zi"])))
                d_beta = maximum(abs.(fit.β .- βR))
                d_LLt = maximum(abs.(fit.Λ * fit.Λ' .- ΛR * ΛR'))
                d_phi = phiR === nothing ? 0.0 : maximum(abs.(log.(fit.phi) .- log.(phiR)))
                @info "zi twin $name" d_opt d_cross_j d_cross_r d_rerun d_zi d_beta d_LLt d_phi

                # Tolerances: logLik quantities at 1e-6 absolute (the measured gaps are
                # 1e-8 or smaller; 1e-6 is the ledger's light-cell bound). Parameters at
                # 1e-3: both optimisers stop on a gradient tolerance on a flat surface,
                # so parameters agree to about the square root of the objective gap.
                @test d_opt < 1e-6
                @test d_cross_j < 1e-6
                @test d_cross_r < 1e-6
                @test d_rerun < 1e-6
                @test d_zi < 1e-3
                @test d_beta < 1e-3
                @test d_LLt < 1e-3
                @test d_phi < 1e-3
            end
        end

        # Why the R names do not route to Julia's own ZIPoisson fitter: its Laplace
        # log-det uses the Fisher count weight, so at R's optimum its marginal is not
        # R's logLik. If that gap is ever closed, this test fails and the R name can be
        # re-pointed at the existing route.
        fx = fixture["zi_poisson"]; r = fx["r_reference"]
        Y, _ = _load_zi_csv(joinpath(_ZI_FIXTURE_DIR, fx["data_file"]), p, Int(fx["n_unit"]))
        ll_fisher = zip_marginal_loglik_laplace(Float64.(Y), reshape(Float64.(r["Lambda_B"]), p, 1),
                                                Float64.(r["logit_zi"]), Float64.(r["beta"]))
        gap = abs(ll_fisher - Float64(r["loglik"]))
        @info "existing ZIPoisson route at R's optimum" gap
        @test gap > 1e-4
    end
end
