## Generate the gllvmTMB P1 receipts for the GLLVModels.jl temporal port, slice 2:
## the temporal source composed with ordinary unit / unit_obs terms
## (indep, dep, latent) and the `(1 | unit)` random intercept.
##
## Pin: gllvmTMB 9539352f66f2db2cc26b1c393e67212a359b60c9 (DESCRIPTION 0.7.1),
## installed into a temporary library from a detached worktree:
##
##   git -C <gllvmTMB> worktree add --detach <scratch>/gllvmTMB-p1 9539352f6
##   R CMD INSTALL --library=<scratch>/Rlib <scratch>/gllvmTMB-p1
##   RLIB=<scratch>/Rlib Rscript test/fixtures/temporal_p1/generate_temporal_p1_slice2.R
##
## Stage 1 (default) writes composed.toml. Stage 2 (`Rscript ... cross`) reads
## julia_optima_composed.csv, written by
## test/fixtures/temporal_p1/julia_optima_composed.jl, and writes
## composed_cross.toml: R's objective at Julia's optimum for every fit
## (cross-objective, the Julia-to-R direction).
##
## Data: R's own slice-2 test fixtures at P1 (test-temporal-sixth-source-engine.R,
## test-temporal-program-composed-simulation.R, test-temporal-sixth-source-oracles.R)
## plus simulated panels with an interior optimum. Every data column is recorded
## literally; value_sha256 is the sha256 of the little-endian float64 bytes of
## the response column.

.libPaths(c(Sys.getenv("RLIB"), .libPaths()))
suppressMessages(library(gllvmTMB))
stopifnot(as.character(packageVersion("gllvmTMB")) == "0.7.1")

args <- commandArgs(trailingOnly = TRUE)
stage <- if (length(args)) args[[1L]] else "stage1"
out_dir <- file.path("test", "fixtures", "temporal_p1")
if (!dir.exists(out_dir)) stop("run from the GLLVModels.jl repository root")

## ---- TOML helpers (as in generate_temporal_p1.R) -------------------------
tnum <- function(x) {
  vapply(x, function(v) {
    if (is.na(v) && !is.nan(v)) return("\"NA\"")
    if (is.nan(v)) return("nan")
    if (is.infinite(v)) return(if (v > 0) "inf" else "-inf")
    s <- sprintf("%.17g", v)
    if (!grepl("[.eE]", s)) s <- paste0(s, ".0")
    s
  }, character(1))
}
tstr <- function(x) paste0("\"", gsub("\"", "\\\\\"", as.character(x)), "\"")
tarr <- function(x, fmt = tnum) if (!length(x)) "[]" else paste0("[", paste(fmt(x), collapse = ", "), "]")
kv <- function(con, key, value) cat(key, " = ", value, "\n", sep = "", file = con)
sha_f64 <- function(x) digest::digest(writeBin(as.numeric(x), raw(), endian = "little"),
  algo = "sha256", serialize = FALSE)
header <- function(con, what) {
  cat("# gllvmTMB P1 receipt: ", what, "\n", sep = "", file = con)
  cat("# Generated by test/fixtures/temporal_p1/generate_temporal_p1_slice2.R; do not edit by hand.\n", file = con)
  kv(con, "gllvmTMB_commit", tstr("9539352f66f2db2cc26b1c393e67212a359b60c9"))
  kv(con, "gllvmTMB_version", tstr(as.character(packageVersion("gllvmTMB"))))
  kv(con, "TMB_version", tstr(as.character(packageVersion("TMB"))))
  kv(con, "R_version", tstr(paste(R.version$major, R.version$minor, sep = ".")))
  cat("\n", file = con)
}
str_cols <- c("series", "trait", "measurement", "unit_obs", "within_unit")
write_dataset <- function(con, name, d) {
  cat("[datasets.", name, "]\n", sep = "", file = con)
  for (col in names(d)) {
    if (col == "value") next
    if (col %in% str_cols) kv(con, col, tarr(as.character(d[[col]]), tstr))
    else kv(con, col, tarr(as.numeric(d[[col]])))
  }
  kv(con, "value", tarr(d$value))
  kv(con, "value_sha256", tstr(sha_f64(d$value)))
  cat("\n", file = con)
}

## ---- Data fixtures -------------------------------------------------------
engine_data <- function() {                        # sixth-source-engine.R:1-10
  out <- expand.grid(series = paste0("s", 1:3), occasion = c(1L, 3L, 7L),
    trait = paste0("t", 1:3), KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
  out$within_unit <- out$series
  out$value <- with(out, as.numeric(factor(trait)) + occasion / 10)
  out
}
composed_data <- function() {                      # program-composed-simulation.R:1-10
  data <- expand.grid(series = paste0("s", 1:3), occasion = c(1L, 3L, 7L),
    trait = paste0("t", 1:3), KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
  data$unit_obs <- paste(data$series, data$occasion)
  data$value <- with(data, as.numeric(factor(trait)) + occasion / 10)
  data
}
oracle_data <- function() {                        # sixth-source-oracles.R:1-11, :318
  out <- expand.grid(series = c("a", "b"), occasion = c(1L, 3L, 7L),
    trait = paste0("t", 1:3), KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
  out$elapsed <- c(0, 1.25, 4.5)[match(out$occasion, c(1L, 3L, 7L))]
  out$value <- with(out, 0.15 * as.integer(factor(trait)) +
    0.1 * occasion + as.integer(factor(series)) / 7)
  out$unit_obs <- paste(out$series, out$occasion)
  out
}
## Simulated panels with an interior optimum (not R test fixtures): temporal
## indep AR1/OU states plus a stable unit effect (Sigma_B), a unit_obs effect
## (Sigma_W, replicated panels only) and residual noise.
sim_composed <- function(seed, times, time_col, structure, n_series, n_rep = 1L,
                         row_obs = FALSE) {
  set.seed(seed)
  traits <- paste0("t", 1:3)
  psi <- c(0.35, 0.45, 0.30); beta <- c(1, -0.5, 0.25)
  lam_B <- c(0.7, -0.4, 0.5); psi_B <- c(0.15, 0.20, 0.10)
  lam_W <- c(0.5, 0.3, -0.4); psi_W <- c(0.10, 0.15, 0.12)
  sigma <- 0.5; phi <- 0.6; kappa <- 0.6
  rows <- list()
  for (g in seq_len(n_series)) {
    b <- lam_B * rnorm(1) + sqrt(psi_B) * rnorm(3)
    q <- matrix(0, 3L, length(times))
    for (k in seq_along(times)) {
      if (k == 1L) q[, k] <- sqrt(psi) * rnorm(3) else {
        a <- if (structure == "ar1") phi^(times[k] - times[k - 1L]) else exp(-kappa * (times[k] - times[k - 1L]))
        q[, k] <- a * q[, k - 1L] + sqrt(psi) * sqrt(1 - a^2) * rnorm(3)
      }
      w <- if (n_rep > 1L) lam_W * rnorm(1) + sqrt(psi_W) * rnorm(3) else numeric(3)
      for (r in seq_len(n_rep)) {
        wr <- if (row_obs) lam_W * rnorm(1) + sqrt(psi_W) * rnorm(3) else w
        for (j in 1:3) {
          rows[[length(rows) + 1L]] <- data.frame(series = sprintf("g%02d", g),
            time = times[k], measurement = paste0("m", r), trait = traits[j],
            value = beta[j] + b[j] + q[j, k] + wr[j] + sigma * rnorm(1),
            stringsAsFactors = FALSE)
        }
      }
    }
  }
  d <- do.call(rbind, rows)
  names(d)[names(d) == "time"] <- time_col
  if (n_rep == 1L) d$measurement <- NULL
  d$unit_obs <- if (row_obs) paste(d$series, d[[time_col]], d$measurement) else
    paste(d$series, d[[time_col]])
  d
}
datasets <- list(
  engine = engine_data(),
  composed = composed_data(),
  oracle = oracle_data(),
  sim_u = sim_composed(261001L, c(1, 2, 3, 5, 6, 8, 9, 10), "occasion", "ar1", 24L),
  sim_uo = sim_composed(261002L, c(0, 0.5, 1.2, 1.6, 2.7, 3.1, 4.4, 5.0), "elapsed", "ou", 24L),
  sim_r = sim_composed(261003L, c(1, 2, 4, 5, 6, 8), "occasion", "ar1", 14L, n_rep = 2L),
  sim_rw = sim_composed(261004L, c(1, 2, 4, 5, 6, 8), "occasion", "ar1", 14L, n_rep = 2L,
    row_obs = TRUE)
)

## ---- Fit cells -----------------------------------------------------------
## `temporal` is the R marker call; `terms` the ordinary R terms; `jterms` the
## same terms in the Julia `structure` Expr syntax.
cell <- function(id, dataset, temporal, jtemporal, terms = character(0),
                 jterms = character(0), unit_obs = "") {
  list(id = id, dataset = dataset, temporal = temporal, jtemporal = jtemporal,
    terms = terms, jterms = jterms, unit_obs = unit_obs)
}
T_I <- "temporal_indep(0 + trait | series, time = occasion)"
J_I <- "temporal_indep(:(0 + trait | series), :occasion)"
T_IE <- "temporal_indep(0 + trait | series, time = elapsed, structure = \"ou\")"
J_IE <- "temporal_indep(:(0 + trait | series), :elapsed; structure = :ou)"
T_L <- "temporal_latent(0 + trait | series, time = occasion)"
J_L <- "temporal_latent(:(0 + trait | series), :occasion)"
T_LU <- "temporal_latent(0 + trait | series, time = occasion, unique = TRUE)"
J_LU <- "temporal_latent(:(0 + trait | series), :occasion; unique = true)"
T_LUE <- "temporal_latent(0 + trait | series, time = elapsed, structure = \"ou\", unique = TRUE)"
J_LUE <- "temporal_latent(:(0 + trait | series), :elapsed; structure = :ou, unique = true)"
T_D <- "temporal_dep(0 + trait | series, time = occasion)"
J_D <- "temporal_dep(:(0 + trait | series), :occasion)"
T_IR <- "temporal_indep(0 + trait | series, time = occasion, replicate = measurement)"
J_IR <- "temporal_indep(:(0 + trait | series), :occasion; replicate = :measurement)"
T_LUR <- "temporal_latent(0 + trait | series, time = occasion, replicate = measurement, unique = TRUE)"
J_LUR <- "temporal_latent(:(0 + trait | series), :occasion; replicate = :measurement, unique = true)"

cells <- list()
add <- function(x) cells[[length(cells) + 1L]] <<- x
## R's six engine cells (sixth-source-engine.R:69), unit_obs = within_unit.
for (level in c("series", "within_unit")) {
  add(cell(paste0("engine__indep_", level), "engine", T_I, J_I,
    sprintf("indep(0 + trait | %s)", level), sprintf("indep(0 + trait | %s)", level), "within_unit"))
  add(cell(paste0("engine__dep_", level), "engine", T_I, J_I,
    sprintf("dep(0 + trait | %s)", level), sprintf("dep(0 + trait | %s)", level), "within_unit"))
  add(cell(paste0("engine__latent_", level), "engine", T_I, J_I,
    sprintf("latent(0 + trait | %s, d = 1)", level), sprintf("latent(0 + trait | %s, d = 1)", level),
    "within_unit"))
}
add(cell("engine__re_int", "engine", T_I, J_I, "(1 | series)", "(1 | series)"))  # engine.R:34
add(cell("engine__latent_B_nounique", "engine", T_I, J_I,               # engine.R:91
  "latent(0 + trait | series, d = 1, unique = FALSE)", "latent(0 + trait | series, d = 1, unique = false)"))
add(cell("composed__indep_BW", "composed", T_I, J_I,                     # composed-simulation.R
  c("indep(0 + trait | series)", "indep(0 + trait | unit_obs)"),
  c("indep(0 + trait | series)", "indep(0 + trait | unit_obs)"), "unit_obs"))
## Interior optima, unreplicated AR1 and OU.
add(cell("sim_u__Tindep_Bindep", "sim_u", T_I, J_I, "indep(0 + trait | series)", "indep(0 + trait | series)"))
add(cell("sim_u__Tindep_Bdep", "sim_u", T_I, J_I, "dep(0 + trait | series)", "dep(0 + trait | series)"))
add(cell("sim_u__Tindep_Blatent", "sim_u", T_I, J_I, "latent(0 + trait | series, d = 1)",
  "latent(0 + trait | series, d = 1)"))
add(cell("sim_u__Tlatent_Bindep", "sim_u", T_L, J_L, "indep(0 + trait | series)", "indep(0 + trait | series)"))
add(cell("sim_u__Tlatentu_Bindep", "sim_u", T_LU, J_LU, "indep(0 + trait | series)", "indep(0 + trait | series)"))
add(cell("sim_u__Tdep_Bindep", "sim_u", T_D, J_D, "indep(0 + trait | series)", "indep(0 + trait | series)"))
add(cell("sim_u__Tindep_reint", "sim_u", T_I, J_I, "(1 | series)", "(1 | series)"))
add(cell("sim_uo__Tindep_Bindep", "sim_uo", T_IE, J_IE, "indep(0 + trait | series)", "indep(0 + trait | series)"))
add(cell("sim_uo__Tlatentu_Blatent", "sim_uo", T_LUE, J_LUE, "latent(0 + trait | series, d = 1)",
  "latent(0 + trait | series, d = 1)"))
## Interior optima, replicated AR1 with a unit_obs = series-occasion effect.
add(cell("sim_r__Tindep_Windep", "sim_r", T_IR, J_IR, "indep(0 + trait | unit_obs)",
  "indep(0 + trait | unit_obs)", "unit_obs"))
add(cell("sim_r__Tindep_Wdep", "sim_r", T_IR, J_IR, "dep(0 + trait | unit_obs)",
  "dep(0 + trait | unit_obs)", "unit_obs"))
add(cell("sim_r__Tindep_Wlatent", "sim_r", T_IR, J_IR, "latent(0 + trait | unit_obs, d = 1)",
  "latent(0 + trait | unit_obs, d = 1)", "unit_obs"))
add(cell("sim_r__Tindep_Bindep_Windep", "sim_r", T_IR, J_IR,
  c("indep(0 + trait | series)", "indep(0 + trait | unit_obs)"),
  c("indep(0 + trait | series)", "indep(0 + trait | unit_obs)"), "unit_obs"))
add(cell("sim_r__Tlatentu_Bindep", "sim_r", T_LUR, J_LUR, "indep(0 + trait | series)",
  "indep(0 + trait | series)", "unit_obs"))
## Replicated, per-row unit_obs diagonal: R suppresses sigma_eps
## (R/fit-multi.R:6959-6967), so log_sigma_eps leaves opt$par.
add(cell("sim_rw__Tindep_Wrow", "sim_rw", T_IR, J_IR, "indep(0 + trait | unit_obs)",
  "indep(0 + trait | unit_obs)", "unit_obs"))
add(cell("sim_rw__Tindep_Wrowlatent", "sim_rw", T_IR, J_IR, "latent(0 + trait | unit_obs, d = 1)",
  "latent(0 + trait | unit_obs, d = 1)", "unit_obs"))

fit_cell <- function(cl, tight = FALSE) {
  rhs <- paste(c("0 + trait", cl$temporal, cl$terms), collapse = " + ")
  form <- as.formula(paste("value ~", rhs))
  control <- if (tight) {
    gllvmTMBcontrol(se = FALSE, optArgs = list(control = list(rel.tol = 1e-14,
      eval.max = 20000, iter.max = 20000)))
  } else gllvmTMBcontrol(se = FALSE)
  args <- list(form, data = datasets[[cl$dataset]], unit = "series", family = gaussian(),
    silent = TRUE, control = control)
  if (nzchar(cl$unit_obs)) args$unit_obs <- cl$unit_obs
  suppressMessages(suppressWarnings(do.call(gllvmTMB, args)))
}
tiers <- function(fit) gllvmTMB:::.gllvmTMB_predict_unhandled_re_tiers(fit, handled = "temporal")

## Deterministic fixed coordinates for the fixed-point receipts: every block is
## set away from R's optimum (oracles.R:120-131 for the temporal blocks).
set_fixed <- function(fit, value = 0.65) {
  fixed <- fit$opt$par
  nm <- names(fixed)
  structure <- fit$temporal$structure
  fixed[nm == "theta_temporal_time"] <- if (identical(structure, "ar1")) atanh(value / (1 - 1e-6)) else log(0.7)
  fixed[nm == "theta_temporal_rr"] <- seq_len(sum(nm == "theta_temporal_rr")) / 5
  fixed[nm == "theta_temporal_diag"] <- log(c(0.45, 0.55, 0.65))
  fixed[nm == "log_sigma_eps"] <- log(0.35)
  fixed[nm == "theta_diag_B"] <- log(c(0.25, 0.35, 0.45))
  fixed[nm == "theta_diag_W"] <- log(c(0.15, 0.20, 0.30))
  fixed[nm == "theta_rr_B"] <- (-1)^seq_len(sum(nm == "theta_rr_B")) * seq_len(sum(nm == "theta_rr_B")) / 7
  fixed[nm == "theta_rr_W"] <- seq_len(sum(nm == "theta_rr_W")) / 9
  fixed[nm == "log_sigma_re_int"] <- log(0.4)
  fixed
}

write_fit <- function(con, cl, fit, tf) {
  cat("[[fits]]\n", file = con)
  kv(con, "id", tstr(cl$id)); kv(con, "dataset", tstr(cl$dataset))
  kv(con, "call", tstr(paste("value ~", paste(c("0 + trait", cl$temporal, cl$terms), collapse = " + "))))
  kv(con, "julia_temporal", tstr(cl$jtemporal)); kv(con, "julia_terms", tarr(cl$jterms, tstr))
  kv(con, "unit", tstr("series")); kv(con, "unit_obs", tstr(cl$unit_obs))
  kv(con, "workflow", tstr(fit$temporal$workflow))
  kv(con, "tiers", tarr(tiers(fit), tstr))
  kv(con, "par_names", tarr(names(fit$opt$par), tstr))
  kv(con, "par", tarr(unname(fit$opt$par)))
  kv(con, "objective", tnum(fit$opt$objective))
  kv(con, "convergence", as.character(fit$opt$convergence))
  kv(con, "gradient_at_par", tarr(as.numeric(fit$tmb_obj$gr(fit$opt$par))))
  kv(con, "log_sigma_eps_full", tnum(fit$tmb_obj$env$parList(fit$opt$par)$log_sigma_eps[1L]))
  kv(con, "sigma_eps", tnum(fit$report$sigma_eps))
  kv(con, "nobs", as.character(nobs(fit)))
  kv(con, "logLik", tnum(as.numeric(logLik(fit))))
  kv(con, "logLik_df", as.character(attr(logLik(fit), "df")))
  kv(con, "AIC", tnum(AIC(fit))); kv(con, "BIC", tnum(BIC(fit)))
  kv(con, "eta", tarr(as.numeric(fit$report$eta)))
  kv(con, "time_value", tnum(extract_temporal(fit)$time$value))
  fx <- set_fixed(fit)
  kv(con, "fixed_par", tarr(unname(fx)))
  kv(con, "fixed_fn", tnum(as.numeric(fit$tmb_obj$fn(fx))))
  kv(con, "fixed_gr", tarr(as.numeric(fit$tmb_obj$gr(fx))))
  if (any(grepl("^latent\\(0 \\+ trait \\| series", cl$terms)) && identical(fit$temporal$mode, "indep")) {
    o <- extract_ordination(fit, level = "unit")
    kv(con, "ordination_row_id", tarr(o$row_id, tstr))
    kv(con, "ordination_scores", tarr(as.numeric(o$scores)))
    kv(con, "ordination_loadings", tarr(as.numeric(o$loadings)))
    kv(con, "ordination_names", tarr(names(o), tstr))
  }
  kv(con, "par_tight", tarr(unname(tf$opt$par)))
  kv(con, "objective_tight", tnum(tf$opt$objective))
  kv(con, "convergence_tight", as.character(tf$opt$convergence))
  kv(con, "gradient_at_par_tight", tarr(as.numeric(tf$tmb_obj$gr(tf$opt$par))))
  cat("\n", file = con)
}

if (identical(stage, "stage1")) {
  con <- file(file.path(out_dir, "composed.toml"), "w")
  header(con, "temporal + ordinary unit / unit_obs fits (opt$par, objective, fn/gr, report)")
  for (nm in names(datasets)) write_dataset(con, nm, datasets[[nm]])
  for (cl in cells) {
    fit <- fit_cell(cl); tf <- fit_cell(cl, tight = TRUE)
    write_fit(con, cl, fit, tf)
  }
  ## sixth-source-oracles.R:318, verbatim coordinates.
  cl <- cell("oracle__indep_BW", "oracle", T_I, J_I,
    c("indep(0 + trait | series)", "indep(0 + trait | unit_obs)"),
    c("indep(0 + trait | series)", "indep(0 + trait | unit_obs)"), "unit_obs")
  fit <- fit_cell(cl)
  fixed <- fit$opt$par
  fixed[names(fixed) == "theta_temporal_time"] <- atanh(0.65 / (1 - 1e-6))
  fixed[names(fixed) == "theta_temporal_diag"] <- log(c(0.45, 0.55, 0.65))
  fixed[names(fixed) == "log_sigma_eps"] <- log(0.35)
  fixed[names(fixed) == "theta_diag_B"] <- log(c(0.25, 0.35, 0.45))
  fixed[names(fixed) == "theta_diag_W"] <- log(c(0.15, 0.20, 0.30))
  cat("[oracle318]\n", file = con)
  kv(con, "dataset", tstr("oracle")); kv(con, "julia_temporal", tstr(cl$jtemporal))
  kv(con, "julia_terms", tarr(cl$jterms, tstr)); kv(con, "unit_obs", tstr(cl$unit_obs))
  kv(con, "par_names", tarr(names(fixed), tstr)); kv(con, "par", tarr(unname(fixed)))
  kv(con, "fn", tnum(as.numeric(fit$tmb_obj$fn(fixed))))
  kv(con, "gr", tarr(as.numeric(fit$tmb_obj$gr(fixed))))
  close(con)
  cat("composed stage written\n")
} else if (identical(stage, "cross")) {
  jo <- utils::read.csv(file.path(out_dir, "julia_optima_composed.csv"), stringsAsFactors = FALSE)
  con <- file(file.path(out_dir, "composed_cross.toml"), "w")
  header(con, "R objective at the Julia optimum, composed fits (cross-objective, Julia to R)")
  for (cl in cells) {
    rows <- jo[jo$fit_id == cl$id, , drop = FALSE]
    if (!nrow(rows)) next
    rows <- rows[order(rows$index), , drop = FALSE]
    fit <- fit_cell(cl)
    stopifnot(nrow(rows) == length(fit$opt$par), identical(rows$name, names(fit$opt$par)))
    cat("[[cells]]\n", file = con)
    kv(con, "id", tstr(cl$id)); kv(con, "julia_par", tarr(rows$value))
    kv(con, "r_fn_at_julia_par", tnum(as.numeric(fit$tmb_obj$fn(rows$value))))
    cat("\n", file = con)
  }
  close(con)
  cat("cross stage written\n")
}
