## Generate the gllvmTMB P1 receipts for the GLLVModels.jl temporal port (slice 1).
##
## Pin: gllvmTMB 9539352f66f2db2cc26b1c393e67212a359b60c9 (DESCRIPTION 0.7.1),
## installed into a temporary library from a detached worktree:
##
##   git -C <gllvmTMB> worktree add --detach <scratch>/gllvmTMB-p1 9539352f6
##   R CMD INSTALL --library=<scratch>/Rlib <scratch>/gllvmTMB-p1
##   RLIB=<scratch>/Rlib Rscript test/fixtures/temporal_p1/generate_temporal_p1.R
##
## Stage 1 (default) writes oracle.toml, fits.toml, forecast.toml, profile.toml
## and compare.toml. Stage 2 (`Rscript ... cross`) reads julia_optima.csv, written
## by test/fixtures/temporal_p1/julia_optima.jl, and writes cross_objective.toml:
## R's objective evaluated at Julia's optimum for every fit (cross-objective,
## the Julia-to-R direction).
##
## Data fixtures are R's own test fixtures at P1 (tests/testthat/test-temporal-*.R)
## plus four simulated panels (sim_ar1, sim_ou, sim_rep, sim_indep) drawn here from the
## temporal model with an interior optimum, so between-optima agreement is
## measurable. Every data column is recorded literally; value_sha256 is the
## sha256 of the little-endian float64 bytes of the response column.

.libPaths(c(Sys.getenv("RLIB"), .libPaths()))
suppressMessages(library(gllvmTMB))
stopifnot(as.character(packageVersion("gllvmTMB")) == "0.7.1")

args <- commandArgs(trailingOnly = TRUE)
stage <- if (length(args)) args[[1L]] else "stage1"
out_dir <- file.path("test", "fixtures", "temporal_p1")
if (!dir.exists(out_dir)) stop("run from the GLLVModels.jl repository root")

## ---- TOML helpers --------------------------------------------------------
tnum <- function(x) {
  vapply(x, function(v) {
    if (is.na(v) && !is.nan(v)) return("\"NA\"")
    if (is.nan(v)) return("nan")
    if (is.infinite(v)) return(if (v > 0) "inf" else "-inf")
    s <- sprintf("%.17g", v)
    if (!grepl("[.eE]", s)) s <- paste0(s, ".0")
    s
  }, character(1))
}
tstr <- function(x) paste0("\"", gsub("\"", "\\\\\"", as.character(x)), "\"")
tarr <- function(x, fmt = tnum) if (!length(x)) "[]" else paste0("[", paste(fmt(x), collapse = ", "), "]")
kv <- function(con, key, value) cat(key, " = ", value, "\n", sep = "", file = con)
sha_f64 <- function(x) digest::digest(writeBin(as.numeric(x), raw(), endian = "little"),
  algo = "sha256", serialize = FALSE)

header <- function(con, what) {
  cat("# gllvmTMB P1 receipt: ", what, "\n", sep = "", file = con)
  cat("# Generated by test/fixtures/temporal_p1/generate_temporal_p1.R; do not edit by hand.\n", file = con)
  kv(con, "gllvmTMB_commit", tstr("9539352f66f2db2cc26b1c393e67212a359b60c9"))
  kv(con, "gllvmTMB_version", tstr(as.character(packageVersion("gllvmTMB"))))
  kv(con, "TMB_version", tstr(as.character(packageVersion("TMB"))))
  kv(con, "R_version", tstr(paste(R.version$major, R.version$minor, sep = ".")))
  cat("\n", file = con)
}

write_dataset <- function(con, name, d, time_cols) {
  cat("[datasets.", name, "]\n", sep = "", file = con)
  kv(con, "series", tarr(as.character(d$series), tstr))
  kv(con, "trait", tarr(as.character(d$trait), tstr))
  for (tc in time_cols) kv(con, tc, tarr(as.numeric(d[[tc]])))
  if (!is.null(d$measurement)) kv(con, "measurement", tarr(as.character(d$measurement), tstr))
  kv(con, "value", tarr(d$value))
  kv(con, "value_sha256", tstr(sha_f64(d$value)))
  cat("\n", file = con)
}

## ---- Data fixtures -------------------------------------------------------
oracle_data <- function() {                       # test-temporal-sixth-source-oracles.R:1-11
  out <- expand.grid(series = c("a", "b"), occasion = c(1L, 3L, 7L),
    trait = paste0("t", 1:3), KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
  out$elapsed <- c(0, 1.25, 4.5)[match(out$occasion, c(1L, 3L, 7L))]
  out$value <- with(out, 0.15 * as.integer(factor(trait)) +
    0.1 * occasion + as.integer(factor(series)) / 7)
  out
}
forecast_data <- function() {                     # test-temporal-program-forecast.R:1-17
  data <- expand.grid(series = c("s1", "s2"), occasion = c(1L, 2L, 3L),
    trait = c("t1", "t2", "t3"), KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
  data$elapsed <- c(0, 1.5, 4)[match(data$occasion, c(1L, 2L, 3L))]
  data$value <- with(data, as.numeric(factor(trait)) / 4 +
    as.numeric(factor(series)) / 5 + occasion / 10)
  data
}
profile_ar1_data <- function() {                  # test-temporal-program-profile.R:2-5
  d <- expand.grid(series = c("a", "b", "c"), occasion = 1:4,
    trait = c("t1", "t2", "t3"), KEEP.OUT.ATTRS = FALSE)
  set.seed(260909L)
  d$value <- as.numeric(factor(d$trait)) + stats::rnorm(nrow(d))
  d
}
profile_ou_data <- function() {                   # test-temporal-program-profile.R:31-33
  d <- expand.grid(series = c("a", "b", "c"), elapsed = c(0, .5, 2),
    trait = c("t1", "t2", "t3"), KEEP.OUT.ATTRS = FALSE)
  set.seed(260918L); d$value <- as.numeric(factor(d$trait)) + stats::rnorm(nrow(d))
  d
}
selection_data <- function() {                    # test-temporal-program-selection.R:2-3
  d <- expand.grid(series = c("a", "b", "c"), occasion = 1:3,
    trait = c("t1", "t2", "t3"), KEEP.OUT.ATTRS = FALSE)
  set.seed(260911L); d$value <- stats::rnorm(nrow(d))
  d
}
## Simulated panels with an interior optimum (not R test fixtures).
sim_panel <- function(seed, times, time_col, structure, n_series = 20L, n_rep = 1L,
                      lambda = c(0.8, -0.5, 0.6)) {
  set.seed(seed)
  traits <- paste0("t", 1:3)
  psi <- c(0.30, 0.40, 0.25); beta <- c(1, -0.5, 0.25)
  sigma <- 0.6; phi <- 0.6; kappa <- 0.6
  rows <- list()
  for (g in seq_len(n_series)) {
    z <- numeric(length(times)); q <- matrix(0, 3L, length(times))
    for (k in seq_along(times)) {
      if (k == 1L) {
        z[k] <- rnorm(1); q[, k] <- sqrt(psi) * rnorm(3)
      } else {
        a <- if (structure == "ar1") phi^(times[k] - times[k - 1L]) else exp(-kappa * (times[k] - times[k - 1L]))
        s <- sqrt(1 - a^2)
        z[k] <- a * z[k - 1L] + s * rnorm(1)
        q[, k] <- a * q[, k - 1L] + sqrt(psi) * s * rnorm(3)
      }
    }
    for (k in seq_along(times)) for (r in seq_len(n_rep)) for (j in 1:3) {
      rows[[length(rows) + 1L]] <- data.frame(series = sprintf("g%02d", g),
        time = times[k], measurement = paste0("m", r), trait = traits[j],
        value = beta[j] + lambda[j] * z[k] + q[j, k] + sigma * rnorm(1),
        stringsAsFactors = FALSE)
    }
  }
  d <- do.call(rbind, rows)
  names(d)[names(d) == "time"] <- time_col
  if (n_rep == 1L) d$measurement <- NULL
  d
}
sim_ar1_data <- function() sim_panel(260927L, c(1, 2, 4, 5, 7, 8, 9, 12, 13, 15), "occasion", "ar1")
sim_ou_data <- function() sim_panel(260928L, c(0, 0.4, 1.1, 1.5, 2.6, 3.0, 4.2, 5.5, 5.9, 7.0), "elapsed", "ou")
sim_rep_data <- function() sim_panel(260929L, c(1, 2, 3, 5, 6, 8), "occasion", "ar1", n_series = 10L, n_rep = 2L)
sim_indep_data <- function() sim_panel(260930L, c(1, 2, 4, 5, 7, 8, 9, 12, 13, 15), "occasion", "ar1",
  lambda = c(0, 0, 0))

datasets <- list(
  oracle = list(d = oracle_data(), time_cols = c("occasion", "elapsed")),
  forecast = list(d = forecast_data(), time_cols = c("occasion", "elapsed")),
  profile_ar1 = list(d = profile_ar1_data(), time_cols = "occasion"),
  profile_ou = list(d = profile_ou_data(), time_cols = "elapsed"),
  selection = list(d = selection_data(), time_cols = "occasion"),
  sim_ar1 = list(d = sim_ar1_data(), time_cols = "occasion"),
  sim_ou = list(d = sim_ou_data(), time_cols = "elapsed"),
  sim_rep = list(d = sim_rep_data(), time_cols = "occasion"),
  sim_indep = list(d = sim_indep_data(), time_cols = "occasion")
)

## ---- Fit cells -----------------------------------------------------------
term_string <- function(mode, structure, time, unique = FALSE, replicate = NULL) {
  extra <- paste0(", time = ", time, ", structure = \"", structure, "\"")
  if (!is.null(replicate)) extra <- paste0(extra, ", replicate = ", replicate)
  if (mode == "latent") extra <- paste0(extra, ", unique = ", if (unique) "TRUE" else "FALSE")
  paste0("temporal_", mode, "(0 + trait | series", extra, ")")
}
## `tight = TRUE` reruns R's own nlminb with a tight relative tolerance, so the
## between-optima comparison is against R's optimum rather than nlminb's default
## stopping point; the default-control fit stays the receipt for R's tests.
fit_cell <- function(d, mode, structure, time, unique = FALSE, replicate = NULL, tight = FALSE) {
  form <- as.formula(paste("value ~ 0 + trait +", term_string(mode, structure, time, unique, replicate)))
  control <- if (tight) {
    gllvmTMBcontrol(se = FALSE, optArgs = list(control = list(rel.tol = 1e-14,
      eval.max = 20000, iter.max = 20000)))
  } else gllvmTMBcontrol(se = FALSE)
  suppressWarnings(gllvmTMB(form, data = d, unit = "series", family = gaussian(),
    silent = TRUE, control = control))
}
cells <- list()
add_cells <- function(dataset, structure, time, modes = c("indep", "dep", "latent", "latent_unique"),
                      replicate = NULL) {
  for (m in modes) {
    mode <- sub("_unique", "", m)
    cells[[length(cells) + 1L]] <<- list(id = paste(dataset, m, structure, sep = "__"),
      dataset = dataset, mode = mode, unique = identical(m, "latent_unique"),
      structure = structure, time = time, replicate = replicate)
  }
}
add_cells("profile_ar1", "ar1", "occasion")
add_cells("profile_ou", "ou", "elapsed", "indep")
add_cells("selection", "ar1", "occasion", "indep")
add_cells("selection", "ou", "occasion", "indep")
add_cells("forecast", "ar1", "occasion", "indep")
add_cells("forecast", "ou", "elapsed", "indep")
add_cells("sim_ar1", "ar1", "occasion")
add_cells("sim_ou", "ou", "elapsed")
add_cells("sim_rep", "ar1", "occasion", c("indep", "dep", "latent_unique"), replicate = "measurement")
add_cells("sim_indep", "ar1", "occasion", "indep")

fits <- list(); tight_fits <- list()
for (cell in cells) {
  fits[[cell$id]] <- fit_cell(datasets[[cell$dataset]]$d, cell$mode, cell$structure,
    cell$time, cell$unique, cell$replicate)
  tight_fits[[cell$id]] <- fit_cell(datasets[[cell$dataset]]$d, cell$mode, cell$structure,
    cell$time, cell$unique, cell$replicate, tight = TRUE)
}

write_fit <- function(con, cell, fit) {
  cat("[[fits]]\n", file = con)
  kv(con, "id", tstr(cell$id)); kv(con, "dataset", tstr(cell$dataset))
  kv(con, "mode", tstr(cell$mode)); kv(con, "unique", if (isTRUE(fit$temporal$unique)) "true" else "false")
  kv(con, "structure", tstr(cell$structure)); kv(con, "time", tstr(cell$time))
  kv(con, "replicate", tstr(if (is.null(cell$replicate)) "" else cell$replicate))
  kv(con, "call", tstr(paste("value ~ 0 + trait +", term_string(cell$mode, cell$structure,
    cell$time, cell$unique, cell$replicate))))
  kv(con, "par_names", tarr(names(fit$opt$par), tstr))
  kv(con, "par", tarr(unname(fit$opt$par)))
  kv(con, "objective", tnum(fit$opt$objective))
  kv(con, "convergence", as.character(fit$opt$convergence))
  kv(con, "message", tstr(fit$opt$message))
  kv(con, "gradient_at_par", tarr(as.numeric(fit$tmb_obj$gr(fit$opt$par))))
  kv(con, "nobs", as.character(nobs(fit)))
  kv(con, "logLik", tnum(as.numeric(logLik(fit))))
  kv(con, "AIC", tnum(AIC(fit))); kv(con, "BIC", tnum(BIC(fit)))
  kv(con, "sigma_eps", tnum(fit$report$sigma_eps))
  et <- extract_temporal(fit)
  kv(con, "time_parameter", tstr(et$time$parameter)); kv(con, "time_value", tnum(et$time$value))
  kv(con, "n_series", as.character(et$parameters$n_series)); kv(con, "n_pairs", as.character(et$parameters$n_pairs))
  kv(con, "workflow", tstr(et$parameters$workflow))
  kv(con, "pair_id", tarr(et$pair_index$pair_id, tstr))
  kv(con, "pair_series", tarr(et$pair_index$series, tstr))
  kv(con, "pair_time", tarr(et$pair_index$time))
  if (!is.null(et$loadings)) {
    kv(con, "loadings_rows", as.character(nrow(et$loadings)))
    kv(con, "loadings", tarr(as.numeric(et$loadings)))      # column-major
    Sigma <- tcrossprod(et$loadings)
    if (nrow(et$variance)) diag(Sigma) <- diag(Sigma) + et$variance$value
  } else {
    Sigma <- diag(et$variance$value, nrow(et$variance))
  }
  kv(con, "Sigma_T", tarr(as.numeric(Sigma)))
  kv(con, "variance_component", tarr(et$variance$component, tstr))
  kv(con, "variance", tarr(et$variance$value))
  kv(con, "temporal_sd", tarr(as.numeric(fit$report$temporal_sd)))
  tf <- tight_fits[[cell$id]]
  kv(con, "par_tight", tarr(unname(tf$opt$par)))
  kv(con, "objective_tight", tnum(tf$opt$objective))
  kv(con, "convergence_tight", as.character(tf$opt$convergence))
  kv(con, "gradient_at_par_tight", tarr(as.numeric(tf$tmb_obj$gr(tf$opt$par))))
  cat("\n", file = con)
}

if (identical(stage, "stage1")) {
  ## fits.toml ------------------------------------------------------------
  con <- file(file.path(out_dir, "fits.toml"), "w")
  header(con, "temporal fits (opt$par, objective, report, extract_temporal)")
  for (nm in names(datasets)) write_dataset(con, nm, datasets[[nm]]$d, datasets[[nm]]$time_cols)
  for (cell in cells) write_fit(con, cell, fits[[cell$id]])
  close(con)

  ## oracle.toml: R objective and gradient at fixed coordinates -----------
  ## (test-temporal-sixth-source-oracles.R:214-248, plus :16 boundary checks)
  set_oracle <- function(fit, structure, value) {       # oracles.R:108-119
    fixed <- fit$opt$par
    fixed[names(fixed) == "theta_temporal_time"] <- if (identical(structure, "ar1")) {
      atanh(value / (1 - 1e-6))
    } else log(value)
    fixed[names(fixed) == "theta_temporal_rr"] <- seq_along(fixed[names(fixed) == "theta_temporal_rr"]) / 5
    fixed[names(fixed) == "theta_temporal_diag"] <- log(c(0.45, 0.55, 0.65))
    fixed[names(fixed) == "log_sigma_eps"] <- log(0.35)
    fixed
  }
  con <- file(file.path(out_dir, "oracle.toml"), "w")
  header(con, "native objective and gradient at fixed coordinates (sixth-source-oracles.R:214)")
  write_dataset(con, "oracle", datasets$oracle$d, datasets$oracle$time_cols)
  specs <- list(c("indep", "ar1", "occasion", FALSE), c("dep", "ar1", "occasion", FALSE),
    c("latent", "ar1", "occasion", FALSE), c("latent", "ar1", "occasion", TRUE),
    c("indep", "ou", "elapsed", FALSE), c("dep", "ou", "elapsed", FALSE),
    c("latent", "ou", "elapsed", FALSE), c("latent", "ou", "elapsed", TRUE))
  for (s in specs) {
    unique <- as.logical(s[[4L]])
    fit <- fit_cell(datasets$oracle$d, s[[1L]], s[[2L]], s[[3L]], unique)
    values <- if (identical(s[[2L]], "ar1")) c(-0.7, 0, 0.65) else 0.7
    thetas <- list()
    for (v in values) thetas[[length(thetas) + 1L]] <- list(label = paste0("value=", v), par = set_oracle(fit, s[[2L]], v))
    base <- set_oracle(fit, s[[2L]], if (identical(s[[2L]], "ar1")) 0.65 else 0.7)
    extremes <- if (identical(s[[2L]], "ar1")) c(-20, 20) else c(-45, 45)
    for (th in extremes) {
      e <- base; e[names(e) == "theta_temporal_time"] <- th
      thetas[[length(thetas) + 1L]] <- list(label = paste0("theta=", th), par = e)
    }
    for (th in thetas) {
      cat("[[cells]]\n", file = con)
      kv(con, "mode", tstr(s[[1L]])); kv(con, "structure", tstr(s[[2L]])); kv(con, "time", tstr(s[[3L]]))
      kv(con, "unique", if (unique) "true" else "false"); kv(con, "label", tstr(th$label))
      kv(con, "par_names", tarr(names(th$par), tstr)); kv(con, "par", tarr(unname(th$par)))
      kv(con, "fn", tnum(as.numeric(fit$tmb_obj$fn(th$par))))
      kv(con, "gr", tarr(as.numeric(fit$tmb_obj$gr(th$par))))
      cat("\n", file = con)
    }
  }
  close(con)

  ## forecast.toml ---------------------------------------------------------
  con <- file(file.path(out_dir, "forecast.toml"), "w")
  header(con, "forecast_temporal (program-forecast.R:47 and :104)")
  fa <- fits[["forecast__indep__ar1"]]
  future <- expand.grid(series = c("s1", "s2"), occasion = c(4L, 5L),
    trait = c("t1", "t2", "t3"), KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
  fc <- forecast_temporal(fa, future, se.fit = TRUE)
  cat("[ar1]\n", file = con)
  kv(con, "fit_id", tstr("forecast__indep__ar1"))
  kv(con, "future_series", tarr(future$series, tstr)); kv(con, "future_occasion", tarr(future$occasion))
  kv(con, "future_trait", tarr(future$trait, tstr))
  kv(con, "est", tarr(fc$est)); kv(con, "se_fit", tarr(fc$se.fit))
  neg <- fa; theta <- match("theta_temporal_time", names(neg$opt$par))
  neg$opt$par[theta] <- atanh(-0.6 / (1 - 1e-6))
  fn <- forecast_temporal(neg, future, se.fit = TRUE)
  kv(con, "negative_par", tarr(unname(neg$opt$par)))
  kv(con, "negative_est", tarr(fn$est)); kv(con, "negative_se_fit", tarr(fn$se.fit))
  cat("\n[ou]\n", file = con)
  fo <- fits[["forecast__indep__ou"]]
  fd <- datasets$forecast$d
  future_ou <- fd[fd$occasion == 3L, c("series", "elapsed", "trait")]
  future_ou$elapsed <- future_ou$elapsed + 2
  fco <- forecast_temporal(fo, future_ou, se.fit = TRUE)
  kv(con, "fit_id", tstr("forecast__indep__ou"))
  kv(con, "future_series", tarr(future_ou$series, tstr)); kv(con, "future_elapsed", tarr(future_ou$elapsed))
  kv(con, "future_trait", tarr(future_ou$trait, tstr))
  kv(con, "est", tarr(fco$est)); kv(con, "se_fit", tarr(fco$se.fit))
  close(con)

  ## profile.toml ----------------------------------------------------------
  con <- file(file.path(out_dir, "profile.toml"), "w")
  header(con, "profile_temporal and TMB::tmbprofile traces (program-profile.R)")
  write_profile <- function(key, fit_id, ystep, ytol, parm_range = NULL) {
    fit <- fits[[fit_id]]
    idx <- match("theta_temporal_time", names(fit$opt$par))
    out <- if (is.null(parm_range)) profile_temporal(fit, ystep = ystep, ytol = ytol) else
      profile_temporal(fit, ystep = ystep, ytol = ytol, parm.range = fit$opt$par[[idx]] + parm_range)
    tr <- TMB::tmbprofile(fit$tmb_obj, name = idx, ystep = ystep, ytol = ytol,
      parm.range = if (is.null(parm_range)) c(-Inf, Inf) else fit$opt$par[[idx]] + parm_range, trace = FALSE)
    cat("[", key, "]\n", sep = "", file = con)
    kv(con, "fit_id", tstr(fit_id)); kv(con, "ystep", tnum(ystep)); kv(con, "ytol", tnum(ytol))
    kv(con, "parm_range_offset", if (is.null(parm_range)) "[]" else tarr(parm_range))
    kv(con, "estimate", tnum(out[["estimate"]])); kv(con, "lower", tnum(out[["lower"]]))
    kv(con, "upper", tnum(out[["upper"]]))
    kv(con, "trace_theta", tarr(tr[[1L]])); kv(con, "trace_value", tarr(tr[[2L]]))
    cat("\n", file = con)
  }
  write_profile("ar1", "profile_ar1__indep__ar1", .25, 1)
  write_profile("ar1_constrained", "profile_ar1__indep__ar1", .1, 1, c(-.01, .01))
  write_profile("ou", "profile_ou__indep__ou", .25, 1)
  write_profile("ar1_default", "profile_ar1__indep__ar1", .5, qchisq(.95, 1) / 2 + 1)
  close(con)

  ## compare.toml ----------------------------------------------------------
  con <- file(file.path(out_dir, "compare.toml"), "w")
  header(con, "compare_temporal (program-selection.R:1, plus all-mode candidates)")
  write_compare <- function(key, ids, labels) {
    args <- setNames(lapply(ids, function(i) fits[[i]]), labels)
    out <- do.call(compare_temporal, args)
    cat("[", key, "]\n", sep = "", file = con)
    kv(con, "fit_ids", tarr(ids, tstr)); kv(con, "model", tarr(out$model, tstr))
    kv(con, "logLik", tarr(out$logLik)); kv(con, "df", tarr(out$df)); kv(con, "AIC", tarr(out$AIC))
    kv(con, "convergence", tarr(out$convergence)); kv(con, "columns", tarr(names(out), tstr))
    cat("\n", file = con)
  }
  write_compare("selection", c("selection__indep__ar1", "selection__indep__ou"), c("ar1", "ou"))
  write_compare("all_modes", c("sim_ar1__indep__ar1", "sim_ar1__dep__ar1", "sim_ar1__latent__ar1",
    "sim_ar1__latent_unique__ar1"), c("indep", "dep", "latent", "latent_unique"))
  write_compare("replicated", c("sim_rep__indep__ar1", "sim_rep__dep__ar1", "sim_rep__latent_unique__ar1"),
    c("indep", "dep", "latent_unique"))
  close(con)
  cat("stage 1 written to", out_dir, "\n")
} else if (identical(stage, "cross")) {
  jo <- utils::read.csv(file.path(out_dir, "julia_optima.csv"), stringsAsFactors = FALSE)
  con <- file(file.path(out_dir, "cross_objective.toml"), "w")
  header(con, "R objective at the Julia optimum (cross-objective, Julia to R)")
  for (cell in cells) {
    rows <- jo[jo$fit_id == cell$id, , drop = FALSE]
    if (!nrow(rows)) next
    rows <- rows[order(rows$index), , drop = FALSE]
    fit <- fits[[cell$id]]
    stopifnot(nrow(rows) == length(fit$opt$par), identical(rows$name, names(fit$opt$par)))
    cat("[[cells]]\n", file = con)
    kv(con, "id", tstr(cell$id)); kv(con, "julia_par", tarr(rows$value))
    kv(con, "r_fn_at_julia_par", tnum(as.numeric(fit$tmb_obj$fn(rows$value))))
    cat("\n", file = con)
  }
  close(con)
  cat("cross stage written\n")
}
