# core070_pin.jl -- Core070 gllvmTMB pin selection (D-294/D-295).
#
# Split out of parity_helpers.jl so this logic is includable and testable
# without RCall: it depends only on TOML and the standard library. Included
# by parity_helpers.jl (for the real parity run) and by
# test/test_core070_pin.jl (a plain unit test, no RCall / no R install).
#
# GLLVM_PARITY_PIN names which entry of tools/core070_oracle_pins.toml this
# file's frozen-reference constants come from -- same switch, same default
# ("P1"), and the same strict-on-unknown behavior as tools/parity_oracle.py's
# Python side of this switch. The TOML file is the shared source of the
# per-pin commit + companion byte hashes; neither this file nor
# tools/core070_build_oracle.py hardcodes its own copy.

using TOML

const _CORE070_PIN_ENV_VAR = "GLLVM_PARITY_PIN"
const _CORE070_PINS_FILE = normpath(joinpath(@__DIR__, "..", "..", "tools", "core070_oracle_pins.toml"))

_core070_selected_pin_name() = (raw = get(ENV, _CORE070_PIN_ENV_VAR, nothing); raw === nothing ? "P1" : uppercase(strip(raw)))

function _core070_selected_pin()
    raw = get(ENV, _CORE070_PIN_ENV_VAR, nothing)
    name = _core070_selected_pin_name()
    pins = TOML.parsefile(_CORE070_PINS_FILE)
    haskey(pins, name) || error(
        "$_CORE070_PIN_ENV_VAR=$(repr(raw)) is not a recognized pin. Set " *
        "$_CORE070_PIN_ENV_VAR to one of $(sort(collect(keys(pins)))) " *
        "(case/whitespace insensitive), or leave it unset to use the default (P1)."
    )
    return pins[name]
end

const _CORE070_PIN = _core070_selected_pin()
const _CORE070_REFERENCE_COMMIT = _CORE070_PIN["reference_commit"]
const _CORE070_NAMESPACE_SHA256 = _CORE070_PIN["namespace_sha256"]
const _CORE070_SOURCE_TREE_SHA256 = _CORE070_PIN["source_tree_sha256"]
const _CORE070_ARCHIVE_SHA256 = _CORE070_PIN["archive_sha256"]

# Runner manifest per pin. P0 keeps the historical frozen-r070-contract.toml
# (unchanged); P1 reads the copy regenerated by
# tools/core070_covariance_p1_contract.py, whose own reference_commit is P1.
# Any other pin falls back to the P0 path, which the guard below then refuses.
const _CORE070_FROZEN_CONTRACT_REL = Dict(
    "P0" => "docs/dev-log/core070/frozen-r070-contract.toml",
    "P1" => "docs/dev-log/core070/true-parity-latest/frozen-r070-contract-p1.toml",
)
_core070_frozen_contract_rel() = get(_CORE070_FROZEN_CONTRACT_REL, _core070_selected_pin_name(),
                                     _CORE070_FROZEN_CONTRACT_REL["P0"])

# The frozen-r070-contract.toml manifest is itself pinned to one commit
# (currently P0) and has not been regenerated for any other pin. Nothing in
# Core070CaseRegistry.validate_manifest checks that pin, so a
# GLLVM_PARITY_PIN switch away from the manifest's own frozen commit would
# otherwise consume it silently. Fail loudly instead.
function _core070_check_frozen_contract_pin(manifest::AbstractDict, path::AbstractString)
    contract_commit = get(manifest, "reference_commit", nothing)
    contract_commit == _CORE070_REFERENCE_COMMIT || throw(ArgumentError(
        "$path is frozen at reference_commit $(repr(contract_commit)), but " *
        "$_CORE070_PIN_ENV_VAR selected $(repr(_CORE070_REFERENCE_COMMIT)) -- this " *
        "manifest has not been regenerated for that pin. Set $_CORE070_PIN_ENV_VAR=P0 " *
        "(or leave it unset) to use this manifest, or regenerate it for the selected " *
        "pin before running."
    ))
    return nothing
end

# Oracle build/source receipts per pin (review finding 13). The required run
# copies both into its receipt directory and hashes them into the run's source
# record, so they must belong to the selected pin. P0 keeps the historical
# untracked .unlazy paths; P1 reads the receipts tracked with the covariance
# evidence (written by tools/core070_build_oracle.py for the P1 build). An
# unregistered pin is an error, never a silent P0 fallback.
const _CORE070_ORACLE_RECEIPTS_REL = Dict(
    "P0" => (build = ".unlazy/core070-aghq/oracle-receipts/build.json",
             source = ".unlazy/core070-aghq/oracle-source/source.json"),
    "P1" => (build = "docs/dev-log/core070/true-parity-latest/receipts/covariance/oracle/build.json",
             source = "docs/dev-log/core070/true-parity-latest/receipts/covariance/oracle/source.json"),
)

function _core070_oracle_receipts_rel()
    name = _core070_selected_pin_name()
    haskey(_CORE070_ORACLE_RECEIPTS_REL, name) ||
        error("no oracle build/source receipt paths are registered for pin $(repr(name))")
    return _CORE070_ORACLE_RECEIPTS_REL[name]
end

# Top-level string field of a receipt JSON written by tools/core070_build_oracle.py
# (json.dumps(indent=2, sort_keys=True)): a top-level key sits at exactly two
# spaces of indent, so nested keys (source.json's per-file hashes) never match.
# Exactly one match is required. Kept regex-only so this file needs no JSON package.
function _core070_json_top_string(text::AbstractString, key::AbstractString)
    hits = collect(eachmatch(Regex("^  \"" * key * "\": \"([^\"]*)\"", "m"), text))
    length(hits) == 1 || throw(ArgumentError(
        "oracle receipt has $(length(hits)) top-level \"$key\" string fields, expected exactly one"))
    return String(hits[1].captures[1])
end

# Validate a build.json (kind = :build) or source.json (kind = :source) against the
# selected pin before it is used; throws naming the first mismatching field.
function _core070_check_oracle_receipt(text::AbstractString, rel::AbstractString, kind::Symbol)
    keys = kind === :build ? ("reference_commit", "source_tree_sha256", "archive_sha256") :
           kind === :source ? ("reference_commit", "source_tree_sha256", "archive_sha256", "namespace_sha256") :
           throw(ArgumentError("unknown oracle receipt kind $(repr(kind))"))
    for key in keys
        got = _core070_json_top_string(text, key)
        got == _CORE070_PIN[key] || throw(ArgumentError(
            "oracle $kind receipt $rel has $key = $(repr(got)), but $_CORE070_PIN_ENV_VAR=" *
            "$(_core070_selected_pin_name()) pins $(repr(_CORE070_PIN[key]))"))
    end
    return nothing
end
