#!/usr/bin/env Rscript
# Generates the P1 twin fixture for GLLVModels.jl's chibar2_pvalue()/variance_lrt()
# against gllvmTMB's R/chibar.R at pin P1 (9539352f66f2db2cc26b1c393e67212a359b60c9).
#
# Run from a temporary R library with gllvmTMB installed at that exact pin:
#   R_LIBS_USER=<scratch>/Rlib Rscript generate_chibar2_p1_fixture.R <out.toml>
#
# Grid covers: LRT in {negative, zero, tiny positive, textbook, large} x q in {1,2,3},
# plus the literal inputs from gllvmTMB's own test-select-lv-anova.R chibar2_pvalue()/
# variance_lrt() unit checks (pin P1), so the fixture also re-derives those assertions.
# Refusal cases (bad q, bad LRT) record the raised condition class, not a numeric value.

args <- commandArgs(trailingOnly = TRUE)
out_path <- if (length(args) >= 1) args[[1]] else "chibar2_p1_fixture.toml"

stopifnot(requireNamespace("gllvmTMB", quietly = TRUE))
pkg_desc <- utils::packageDescription("gllvmTMB")
cat("Loaded gllvmTMB", pkg_desc$Version, "from", find.package("gllvmTMB"), "\n")

chibar2_pvalue <- gllvmTMB::chibar2_pvalue
variance_lrt <- gllvmTMB::variance_lrt

fmt_num <- function(x) if (is.na(x)) "nan" else formatC(x, digits = 17, format = "g")

# --- chibar2_pvalue(LRT, q) grid --------------------------------------------------
LRT_grid <- c(-5, -1e-9, 0, 1e-9, 1e-6, 0.5, 1.0, 2.705543454095404, 3.84,
              5.991464547107979, 7.814727903251179, 10, 12, 15, 50, 100)
q_grid <- 1:3

lines <- c(
  "# P1 twin fixture for chibar2_pvalue()/variance_lrt() -- generated by",
  sprintf("# generate_chibar2_p1_fixture.R against gllvmTMB %s at pin", pkg_desc$Version),
  "# 9539352f66f2db2cc26b1c393e67212a359b60c9 (R/chibar.R).",
  sprintf("r_version = \"%s\"", paste(R.version$major, R.version$minor, sep = ".")),
  sprintf("gllvmtmb_version = \"%s\"", pkg_desc$Version),
  "gllvmtmb_pin_sha = \"9539352f66f2db2cc26b1c393e67212a359b60c9\""
)

for (q in q_grid) {
  for (LRT in LRT_grid) {
    p <- chibar2_pvalue(LRT, q)
    lines <- c(lines, "",
               "[[chibar2_pvalue]]",
               sprintf("LRT = %s", fmt_num(LRT)),
               sprintf("q = %d", as.integer(q)),
               sprintf("pvalue = %s", fmt_num(p)))
  }
}

# --- variance_lrt(ll_full, ll_reduced, n_boundary) cases --------------------------
vlrt_cases <- list(
  list(ll_full = -100.2, ll_reduced = -102.1, n_boundary = 1L),  # docstring example
  list(ll_full = -100.0, ll_reduced = -102.0, n_boundary = 1L),  # R unit test
  list(ll_full = -100.0, ll_reduced = -103.0, n_boundary = 2L),  # R unit test (q=2)
  list(ll_full = -105.0, ll_reduced = -100.0, n_boundary = 1L),  # LRT < 0 -> pvalue 1
  list(ll_full = -50.0,  ll_reduced = -50.0,  n_boundary = 3L)   # LRT == 0 -> pvalue 1
)
for (cs in vlrt_cases) {
  r <- variance_lrt(ll_full = cs$ll_full, ll_reduced = cs$ll_reduced, n_boundary = cs$n_boundary)
  lines <- c(lines, "",
             "[[variance_lrt]]",
             sprintf("ll_full = %s", fmt_num(cs$ll_full)),
             sprintf("ll_reduced = %s", fmt_num(cs$ll_reduced)),
             sprintf("n_boundary = %d", as.integer(cs$n_boundary)),
             sprintf("LRT = %s", fmt_num(r$LRT)),
             sprintf("pvalue = %s", fmt_num(r$pvalue)))
}

# --- refusal cases (record the condition class only, no numeric value) -----------
refuse <- function(expr) {
  cond <- tryCatch({ force(expr); NULL }, error = function(e) e)
  if (is.null(cond)) "no_error" else class(cond)[1]
}
refusal_cases <- list(
  list(case = "q_zero",         class = refuse(chibar2_pvalue(3.84, 0))),
  list(case = "q_non_integer",  class = refuse(chibar2_pvalue(3.84, 1.5))),
  list(case = "q_negative",     class = refuse(chibar2_pvalue(3.84, -1))),
  list(case = "LRT_na",         class = refuse(chibar2_pvalue(NA_real_, 1))),
  list(case = "vlrt_loglik_na", class = refuse(variance_lrt(NA_real_, -102.0)))
)
for (r in refusal_cases) {
  lines <- c(lines, "",
             "[[refusals]]",
             sprintf("case = \"%s\"", r$case),
             sprintf("class = \"%s\"", r$class))
}

writeLines(lines, out_path)
cat("Wrote", out_path, "\n")
