# Deterministic JSON -> TOML conversion of the gllvmTMB anova twin fixture.
#
# generate_gllvmtmb_anova_fixture.R writes gllvmtmb_anova_fixture.json (R's
# jsonlite has a JSON writer; there is no standard R TOML writer). The P1 CI
# job runs `julia --project=. test/test_model_comparison.jl` without the test
# environment, where JSON3 is not available, so the test reads a TOML copy
# (TOML is a Julia stdlib). This script produces that copy:
#
#   julia --project=test test/fixtures/convert_gllvmtmb_anova_fixture_to_toml.jl <in.json>
#
# writes test/fixtures/gllvmtmb_anova_fixture.toml and checks that every value
# round-trips exactly (isequal on the parsed JSON vs the parsed TOML).
# Encoding rules: numbers are carried as the same Int64/Float64 values
# (Float64 printed in shortest round-trip form); JSON null (R NA_character_,
# only in the anova tables' `test` column) becomes the string "NA", matching
# how jsonlite already wrote R's numeric NA ("NA"). Keys are written sorted.

using JSON3, TOML

const IN_PATH  = length(ARGS) >= 1 ? ARGS[1] : joinpath(@__DIR__, "gllvmtmb_anova_fixture.json")
const OUT_PATH = joinpath(@__DIR__, "gllvmtmb_anova_fixture.toml")

plain(x::JSON3.Object) = Dict{String,Any}(String(k) => plain(v) for (k, v) in pairs(x))
plain(x::JSON3.Array)  = Any[plain(v) for v in x]
plain(::Nothing)       = "NA"
plain(x::AbstractString) = String(x)
plain(x::Union{Int64,Float64}) = x
plain(x) = error("unexpected JSON value of type $(typeof(x))")

src = plain(JSON3.read(read(IN_PATH, String)))

open(OUT_PATH, "w") do io
    println(io, "# gllvmTMB anova twin fixture (P1 pin 9539352f66f2db2cc26b1c393e67212a359b60c9).")
    println(io, "# Generated by test/fixtures/generate_gllvmtmb_anova_fixture.R (JSON output),")
    println(io, "# then converted deterministically to TOML by")
    println(io, "# test/fixtures/convert_gllvmtmb_anova_fixture_to_toml.jl (R was not re-run).")
    println(io, "# Every value round-trips exactly; JSON null (R NA_character_) is written as \"NA\".")
    println(io, "# The sha256 of this file is asserted by test/test_model_comparison.jl.")
    TOML.print(io, src; sorted = true)
end

back = TOML.parsefile(OUT_PATH)
isequal(back, src) || error("TOML round-trip mismatch")
println("wrote ", OUT_PATH, " (round-trip exact)")
