"""Regenerate the Core070 family-links and A6 Student-t contracts at gllvmTMB pin P1.

In scope: the family rows the P1 carry scan lists as DANGLING or NO_R_PINS whose
P0 evidence came from a stand-alone R + Julia batch rather than the runparity
harness (the runparity cells read frozen-r070-contract-p1.toml, already
regenerated by tools/core070_covariance_p1_contract.py):

  P0 contract (unchanged)            P1 twin (written here)
  family-links-batch-contract.json   family-links-batch-contract-p1.json  (FAMILY-01-PROBIT, -01-CLOGLOG)
  a6-studentt-contract.json          a6-studentt-contract-p1.json         (FAMILY-09-FIXED-SHAPE, -09-IDENTITY)

The P0 files are read and never written; they stay as history.

What changes, recorded in each output's `regeneration_log`:

  * reference_commit -> P1 (from tools/core070_oracle_pins.toml, not a literal);
  * source_pins (family-links only; the A6 contract has none): recomputed from
    the P1 bytes (`git -C $GLLVMTMB_DIR show <P1>:<path>`), after checking each
    P0 pin against the P0 bytes. At P1 the family-links runner checks them under
    the P1 source tree the oracle was built from (CORE070_P1_R_SOURCE_ROOT);
  * both twins gain `p0_to_p1_r_function_diff`: for each R function the cases
    route through, whether its body is byte-identical at P0 and P1. This is a
    record, not a gate.

Carried verbatim: status, cases (r_call, julia_surface, check, tolerance,
fixture), bound rows, negative controls, approximation note, the A6 fixture and
tolerance description. No case, expectation or tolerance is edited; a P1
mismatch is recorded by the batch as a failure.

Usage:
  GLLVMTMB_DIR=/path/to/gllvmTMB python3 tools/core070_family_p1_contract.py [--check]

--check regenerates in memory and exits nonzero if any tracked P1 contract
differs, so a stale contract is caught without rewriting it.
"""
import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from core070_data_p1_contract import (  # noqa: E402  (same helpers as the data/fit-input twins)
    OUT_DIR, P0_DIR, ROOT, function_body, git, pins, sha_bytes)
import json  # noqa: E402

GENERATOR = "tools/core070_family_p1_contract.py"

# P0 contract stem -> R functions its cases route through -> defining file.
CONTRACTS = {
    "family-links-batch-contract": [
        ("gllvmTMB", "R/gllvmTMB.R"),
        (".gllvm_julia_family_scalar", "R/julia-bridge.R"),
    ],
    "a6-studentt-contract": [
        ("gllvmTMB", "R/gllvmTMB.R"),
        ("student", "R/families.R"),
    ],
}


def function_diff(repo, functions, p0_sha, p1_sha):
    rows = []
    for fn, path in functions:
        b0 = function_body(git(repo, "show", f"{p0_sha}:{path}").decode(), fn)
        b1 = function_body(git(repo, "show", f"{p1_sha}:{path}").decode(), fn)
        if b0 is None or b1 is None:
            raise SystemExit(f"{fn} not found in {path} at {'P0' if b0 is None else 'P1'}")
        rows.append({"function": fn, "file": path,
                     "body_identical_p0_p1": b0 == b1,
                     "body_sha256_p0": sha_bytes(b0.encode()),
                     "body_sha256_p1": sha_bytes(b1.encode())})
    return rows


def build(repo, stem):
    p0, p1 = pins()
    src = P0_DIR / f"{stem}.json"
    contract = json.loads(src.read_text())
    if contract["reference_commit"] != p0["reference_commit"]:
        raise SystemExit(f"{src.name} is not pinned at P0")
    log = [{"field": "reference_commit", "p0": contract["reference_commit"], "p1": p1["reference_commit"]}]
    contract["reference_commit"] = p1["reference_commit"]
    if "source_pins" in contract:
        new = {}
        for rel, old in contract["source_pins"].items():
            if not rel.startswith("R/"):
                raise SystemExit(f"unexpected source pin path {rel}")
            if sha_bytes(git(repo, "show", f"{p0['reference_commit']}:{rel}")) != old:
                raise SystemExit(f"{src.name} source pin {rel} does not match the P0 bytes; refuse")
            new[rel] = sha_bytes(git(repo, "show", f"{p1['reference_commit']}:{rel}"))
            log.append({"field": f"source_pins[{rel}]", "p0": old, "p1": new[rel], "changed": old != new[rel]})
        contract["source_pins"] = new
    contract["p0_contract"] = str(src.relative_to(ROOT))
    contract["p0_contract_sha256"] = sha_bytes(src.read_bytes())
    contract["p0_to_p1_r_function_diff"] = function_diff(repo, CONTRACTS[stem], p0["reference_commit"],
                                                         p1["reference_commit"])
    contract["regeneration_log"] = {
        "generator": GENERATOR,
        "changes": log,
        "carried_verbatim": "status, cases (r_call, julia_surface, check, tolerance, fixture), bound rows, "
                            "negative controls, approximation note, fixture and tolerance descriptions. No case, "
                            "expectation or tolerance was edited; a P1 mismatch is recorded by the batch as a "
                            "failure.",
    }
    return json.dumps(contract, indent=2) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    repo = os.environ.get("GLLVMTMB_DIR")
    if not repo:
        raise SystemExit("set GLLVMTMB_DIR to a gllvmTMB clone that contains the P1 commit")
    outputs = {OUT_DIR / f"{stem}-p1.json": build(repo, stem) for stem in CONTRACTS}
    if args.check:
        stale = [str(p.relative_to(ROOT)) for p, t in outputs.items() if not p.exists() or p.read_text() != t]
        if stale:
            print("STALE " + " ".join(stale))
            sys.exit(1)
        print("CORE070_FAMILY_P1_CONTRACTS_CURRENT")
        return
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for p, t in outputs.items():
        p.write_text(t)
        print(f"wrote {p.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
