# Retained evidence runner for the isdm manifest-area admission batch (20 cases).
# Replays pinned R admission-predicate functions against a frozen fixture; no
# fitted model, no Julia call -- see docs/dev-log/core070/isdm-batch-contract.json
# for why (GLLVModels.jl has no public isdm_sources()/isdm_source() surface yet).
#
# Usage:
#   Rscript --vanilla tools/core070_isdm_batch.R <source-root> <destination>
#   GLLVM_PARITY_PIN=P1 CORE070_P1_ORACLE_LIBRARY=<P1 library> \
#     Rscript --vanilla tools/core070_isdm_batch.R <P1 source tree> <destination>
#
# <source-root> is a directory containing R/isdm-sources.R, R/fit-multi.R,
# R/offset.R (the frozen gllvmTMB source readback, e.g.
# .unlazy/core070-aghq/oracle-source/readback). <destination> must not exist.

args <- commandArgs(TRUE)
stopifnot(length(args) == 2L)
source_root <- normalizePath(args[[1]], mustWork = TRUE)
destination <- args[[2]]
stopifnot(!dir.exists(destination))

root <- normalizePath(".")
suppressPackageStartupMessages(library(jsonlite))
stopifnot(requireNamespace("cli", quietly = TRUE))

sha256_file <- function(path) {
  command <- if (nzchar(Sys.which("sha256sum"))) "sha256sum" else "shasum"
  # system2() does not quote its arguments; shQuote keeps a path with spaces one argument.
  argv <- if (identical(command, "sha256sum")) shQuote(path) else c("-a", "256", shQuote(path))
  line <- system2(command, argv, stdout = TRUE, stderr = TRUE)
  stopifnot(is.null(attr(line, "status")), length(line) >= 1L)
  sub("[[:space:]].*$", "", line[[1L]])
}

# Pin switch (D-294/D-295): GLLVM_PARITY_PIN unset means P1; "P0" keeps the frozen
# P0 contract; "P1" reads the twin regenerated by
# tools/core070_isdm_p1_contract.py (reference_commit = P1, source_pins
# recomputed from the P1 bytes, cases verbatim), and <source-root> must then be
# the P1 R source tree the oracle was built from. Any other value stops here
# rather than falling back to P0.
parity_pin <- toupper(trimws(Sys.getenv("GLLVM_PARITY_PIN", "P1")))
if (!parity_pin %in% c("P0", "P1")) stop("GLLVM_PARITY_PIN must be P0 or P1, got '", parity_pin, "'")
expected_reference <- if (identical(parity_pin, "P1"))
  "9539352f66f2db2cc26b1c393e67212a359b60c9" else "b4d5fee64def88bc768dda1f1f77c29b295edd86"
contract_path <- file.path(root, if (identical(parity_pin, "P1"))
  "docs/dev-log/core070/true-parity-latest/isdm-batch-contract-p1.json" else
  "docs/dev-log/core070/isdm-batch-contract.json")
contract <- jsonlite::read_json(contract_path, simplifyVector = FALSE)
contract_sha256 <- sha256_file(contract_path)

stopifnot(identical(contract$reference_commit, expected_reference))
cases <- contract$cases
stopifnot(length(cases) == contract$expected_case_count,
          length(unique(vapply(cases, `[[`, "", "manifest_case_id"))) == length(cases))

# --- validate and load pinned source functions -----------------------------
source_pins <- contract$source_pins
loaded_functions <- contract$loaded_functions
stopifnot(setequal(names(source_pins), names(loaded_functions)))

env <- new.env(parent = globalenv())
source_pins_seen <- list()
for (rel in names(source_pins)) {
  path <- file.path(source_root, rel)
  stopifnot(file.exists(path))
  digest <- sha256_file(path)
  stopifnot(identical(digest, source_pins[[rel]]))
  source_pins_seen[[rel]] <- digest
  wanted <- unlist(loaded_functions[[rel]])
  loaded <- character()
  for (x in parse(path)) {
    if (!is.call(x) || !identical(x[[1L]], as.name("<-"))) next
    name <- as.character(x[[2L]])
    if (length(name) != 1L || !name %in% wanted) next
    stopifnot(is.call(x[[3L]]), identical(x[[3L]][[1L]], as.name("function")),
              !name %in% loaded)
    eval(x, env)
    loaded <- c(loaded, name)
  }
  stopifnot(setequal(wanted, loaded))
}

# R/offset.R also defines a numeric constant that gll_prepare_offset() needs;
# load it the same guarded way (no other top-level code from offset.R runs).
offset_path <- file.path(source_root, "R/offset.R")
constants <- Filter(function(x) is.call(x) && identical(x[[1L]], as.name("<-")) &&
                       identical(x[[2L]], as.name(".gll_offset_count_family_ids")),
                     parse(offset_path))
stopifnot(length(constants) == 1L)
rhs <- constants[[1L]][[3L]]
stopifnot(is.call(rhs), identical(rhs[[1L]], as.name("c")),
          all(vapply(as.list(rhs)[-1L], is.numeric, logical(1L))))
eval(constants[[1L]], env)

# --- validate and load the frozen fixture -----------------------------------
fixture_path <- file.path(root, contract$fixture)
fixture_sha256 <- sha256_file(fixture_path)
stopifnot(identical(fixture_sha256, contract$fixture_sha256))
sys.source(fixture_path, envir = env)

# Oracle source-pin marker and version (same rule as the data and inference
# runners, tools/core070_source_pin.R). This batch parses R source rather than
# loading gllvmTMB, so at P1 the oracle library the P1 source tree was built
# into is named by CORE070_P1_ORACLE_LIBRARY; its CORE070_SOURCE_PIN.toml marker
# and installed version must match the P1 pin. At P0 no library is involved.
# The marker path is recorded relative to the library, so the tracked receipt
# names no host path.
source_pin <- NULL
if (identical(parity_pin, "P1")) {
  oracle_library <- Sys.getenv("CORE070_P1_ORACLE_LIBRARY", "")
  if (!nzchar(oracle_library)) stop("GLLVM_PARITY_PIN=P1 needs CORE070_P1_ORACLE_LIBRARY (the P1 oracle library)")
  oracle_library <- normalizePath(oracle_library, mustWork = TRUE)
  .libPaths(c(oracle_library, .libPaths()))
  stopifnot(normalizePath(find.package("gllvmTMB")) == normalizePath(file.path(oracle_library, "gllvmTMB")))
  source(file.path(root, "tools/core070_source_pin.R"))
  source_pin <- core070_source_pin(root, oracle_library, parity_pin, expected_reference)
  source_pin$marker_path <- "gllvmTMB/CORE070_SOURCE_PIN.toml"
}

# --- evaluate every case in an isolated environment -------------------------
# The destination is created only after the pin checks pass, so a refused run
# leaves nothing behind.
dir.create(destination, recursive = TRUE)
raw_lines <- character(0)
diag_lines <- character(0)
result_cases <- vector("list", length(cases))
all_ok <- TRUE

for (i in seq_along(cases)) {
  case <- cases[[i]]
  t0 <- Sys.time()
  result <- tryCatch(
    eval(parse(text = case$expression), new.env(parent = env)),
    error = identity
  )
  elapsed <- as.numeric(Sys.time() - t0, units = "secs")
  is_error <- inherits(result, "error")
  if (identical(case$expected, "ERROR")) {
    ok <- is_error && grepl(case$error_contains,
                            gsub("[[:space:]]+", " ", conditionMessage(result)),
                            fixed = TRUE)
    actual_value <- if (is_error) conditionMessage(result) else NA_character_
  } else {
    ok <- !is_error && isTRUE(result)
    actual_value <- if (is_error) conditionMessage(result) else isTRUE(result)
  }
  if (is_error) {
    diag_lines <- c(diag_lines,
                     paste0(case$manifest_case_id, ": ", conditionMessage(result)))
  }
  all_ok <- all_ok && ok
  raw_lines <- c(raw_lines,
                 paste(case$manifest_case_id, if (ok) "PASS" else "FAIL", sep = "\t"))
  result_cases[[i]] <- list(
    manifest_case_id = case$manifest_case_id,
    admission_case_id = case$admission_case_id,
    source_id = case$source_id,
    expression = case$expression,
    expected = case$expected,
    error_contains = case$error_contains,
    negative_control = case$negative_control,
    actual = actual_value,
    ok = ok,
    elapsed_seconds = elapsed
  )
}

raw_path <- file.path(destination, "raw.tsv")
writeLines(raw_lines, raw_path)
diag_path <- file.path(destination, "diagnostics.log")
writeLines(diag_lines, diag_path)

results <- list(
  status = if (all_ok) "PASS" else "FAIL",
  area = "isdm",
  scope = "CORE070_ISDM_BATCH",
  reference_commit = contract$reference_commit,
  contract_sha256 = contract_sha256,
  source_pins = source_pins_seen,
  fixture_sha256 = fixture_sha256,
  case_count = length(cases),
  generated_at = format(Sys.time(), "%Y-%m-%dT%H:%M:%S%z"),
  r_version = R.version.string,
  cases = result_cases,
  all_checks = all_ok
)
if (!is.null(source_pin)) results <- c(results, list(gllvmTMB_version = source_pin$version, source_pin = source_pin))
results_path <- file.path(destination, "isdm-batch-results.json")
jsonlite::write_json(results, results_path, auto_unbox = TRUE, pretty = TRUE,
                      null = "null", na = "null")

receipt <- list(
  status = if (all_ok) "PASS" else "FAIL",
  scope = "CORE070_ISDM_BATCH",
  reference_commit = contract$reference_commit,
  contract_sha256 = contract_sha256,
  source_pins = source_pins_seen,
  fixture_sha256 = fixture_sha256,
  source_unchanged = TRUE,
  case_count = length(cases),
  expected_case_ids = vapply(cases, `[[`, "", "manifest_case_id"),
  results_sha256 = sha256_file(results_path),
  raw_sha256 = sha256_file(raw_path),
  diagnostics_sha256 = sha256_file(diag_path),
  r_runtime = R.version.string
)
if (!is.null(source_pin)) receipt <- c(receipt, list(gllvmTMB_version = source_pin$version, source_pin = source_pin))
receipt_path <- file.path(destination, "receipt.json")
jsonlite::write_json(receipt, receipt_path, auto_unbox = TRUE, pretty = TRUE)

cat("CORE070_ISDM_BATCH_", receipt$status, "\n", sep = "")
quit(status = if (all_ok) 0L else 1L)
