"""Verify the surface-conversion batch: 20 BLOCKED_NEEDS_JULIA_SURFACE
ledger rows converted to bound cases (postfit/, namespace/, inference/
prefixes, evidence naming a function that now exists in src/GLLVModels.jl's
export list -- the extractors slice, src/extractors.jl, and the derived-CI
slice, src/confint_derived_wald.jl / src/confint_derived.jl /
src/twolevel.jl). 21 further target rows are recorded in the contract's
`deferred` bucket with an explicit reason and deliberately carry no
fabricated pass. See docs/dev-log/core070/surface-conversion-notes.md for
the full accounting and docs/dev-log/core070/surface-conversion-batch-contract.json
for the frozen 41-row target list (`target_source_ids`).

Two independent checks, mirroring tools/core070_verify_namespace_1_batch.py:

  1. verify_contract() -- structural checks on the frozen contract itself
     (case/deferred counts, no duplicate case_id or source_id, every case's
     quantity is drawn from a known set, negative controls present).
     Needs no retained run.
  2. verify_state(path) -- structural + hash checks against a retained run
     of tools/core070_surface_conversion_batch.R (receipt.json,
     results.tsv, diagnostics.log, julia-results.json).
  3. --self-test -- mutates a SYNTHETIC valid state (built from the frozen
     contract, no retained run required) in >=3 independent ways and
     asserts every mutation is rejected by check_state(). Runs without R,
     Julia, or the frozen library (python3 only). Per the namespace-1/
     postfit-policy precedent's vacuous-pass incident, --self-test NEVER
     substitutes for a real --state check below: passing --self-test alone
     still exits nonzero if --state is not given.
"""
import argparse
from copy import deepcopy
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
import sys as _sys  # noqa: E402
_sys.path.insert(0, str(ROOT / "tools"))
from parity_oracle import R_REF_PINS, SELECTED_PIN  # noqa: E402  (GLLVM_PARITY_PIN; P0 default; unknown pin exits)
# P0 keeps the frozen contract; P1 reads the copy regenerated by
# tools/core070_postfit_p1_contract.py.
CONTRACT_PATH = ROOT / ("docs/dev-log/core070/true-parity-latest/surface-conversion-batch-contract-p1.json"
                        if SELECTED_PIN == "P1" else "docs/dev-log/core070/surface-conversion-batch-contract.json")

REFERENCE_COMMIT = R_REF_PINS[SELECTED_PIN] if SELECTED_PIN == "P1" else "b4d5fee64def88bc768dda1f1f77c29b295edd86"
CASE_COUNT = 20
DEFERRED_COUNT = 21
TARGET_ROW_COUNT = CASE_COUNT + DEFERRED_COUNT  # 41

KNOWN_QUANTITIES = {
    "loadings_crossprod", "lv_predictor", "sigma_unit_total", "sigma_table",
    "communality", "correlations", "cross_correlations", "residual_cov",
    "residual_cor", "ordination_sites", "proportions", "omega", "icc_site",
    "loading_ci_wald_asym", "loading_profile", "profile_ci_total_variance",
    "standard_errors", "repeatability_point", "icc_ci_default", "icc_ci_wald",
    "icc_ci_bootstrap", "cutpoints", "icc_ci_profile",
}
KNOWN_FIXTURES = {"gaussian_small", "twolevel_small", "ordinal_small"}
KNOWN_KINDS = {"point", "ci", "refusal_pair", "bootstrap_structural"}


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def need(ok, message):
    if not ok:
        raise ValueError(message)


def load_contract():
    return json.loads(CONTRACT_PATH.read_text())


# ---------------------------------------------------------------------------
# 1. Contract-only structural checks (no retained run required).
# ---------------------------------------------------------------------------
def verify_contract(contract=None):
    c = contract or load_contract()
    need(c["status"] == "FROZEN_SURFACE_CONVERSION_BATCH_CONTRACT", "wrong contract status")
    need(c["reference_commit"] == REFERENCE_COMMIT, "wrong reference commit")
    need(c["expected_case_count"] == CASE_COUNT, f"expected_case_count drift: {c['expected_case_count']}")
    need(c["expected_deferred_count"] == DEFERRED_COUNT,
         f"expected_deferred_count drift: {c['expected_deferred_count']}")
    need(len(c["cases"]) == CASE_COUNT, f"expected {CASE_COUNT} cases, got {len(c['cases'])}")
    need(len(c["deferred"]) == DEFERRED_COUNT, f"expected {DEFERRED_COUNT} deferred rows, got {len(c['deferred'])}")

    case_source_ids = [x["source_id"] for x in c["cases"]]
    deferred_source_ids = [x["source_id"] for x in c["deferred"]]
    need(len(set(case_source_ids)) == len(case_source_ids), "duplicate source_id within cases[]")
    need(len(set(deferred_source_ids)) == len(deferred_source_ids), "duplicate source_id within deferred[]")
    need(set(case_source_ids).isdisjoint(deferred_source_ids),
         "a source_id appears in both cases[] and deferred[]")

    case_ids = [x["case_id"] for x in c["cases"]]
    need(len(set(case_ids)) == len(case_ids), "duplicate case_id within cases[]")

    all_source_ids = set(case_source_ids) | set(deferred_source_ids)
    need(all_source_ids == set(c["target_source_ids"]),
         "union of cases[]+deferred[] source_ids does not match target_source_ids")
    need(len(c["target_source_ids"]) == TARGET_ROW_COUNT,
         f"target_source_ids has {len(c['target_source_ids'])} entries, expected {TARGET_ROW_COUNT}")
    for sid in all_source_ids:
        need(sid.startswith(("postfit/", "namespace/", "inference/")),
             f"source_id {sid} missing an expected area prefix")

    for row in c["cases"]:
        need(row["kind"] in KNOWN_KINDS, f"{row['case_id']}: unknown kind {row['kind']!r}")
        if row["kind"] in ("refusal_pair", "bootstrap_structural"):
            need(row["tolerance"] is None,
                 f"{row['case_id']}: {row['kind']} case must not carry a numeric tolerance")
        else:
            need(row["quantity"] in KNOWN_QUANTITIES, f"{row['case_id']}: unknown quantity {row['quantity']!r}")
            need(isinstance(row["tolerance"], (int, float)) and row["tolerance"] > 0,
                 f"{row['case_id']}: tolerance must be a positive number")
        need(row["fixture"] in KNOWN_FIXTURES, f"{row['case_id']}: unknown fixture {row['fixture']!r}")

    for row in c["deferred"]:
        need(isinstance(row.get("reason"), str) and len(row["reason"]) > 40,
             f"deferred row {row['source_id']} needs a substantive reason string")

    neg = c["negative_controls"]
    need(len(neg) >= 2, "fewer than 2 negative controls in contract")

    for key, fx in c["fixtures"].items():
        need(key in KNOWN_FIXTURES, f"unexpected fixture key {key!r} in contract.fixtures")
        need("r_formula" in fx and "julia_call" in fx, f"fixture {key} missing r_formula/julia_call")

    return c


# ---------------------------------------------------------------------------
# 2. Retained-state checks (receipt.json + results.tsv + julia-results.json).
# ---------------------------------------------------------------------------
def check_state(contract, receipt, results_lines, julia_report):
    need(receipt["status"] == "PASS", "receipt status is not PASS")
    need(receipt["scope"] == "CORE070_SURFACE_CONVERSION_BATCH", "wrong receipt scope")
    need(receipt["reference_commit"] == REFERENCE_COMMIT, "receipt reference_commit mismatch")
    need(receipt["contract_sha256"] == sha(CONTRACT_PATH),
         "receipt contract_sha256 does not match the on-disk contract")
    need(receipt["source_unchanged"] is True, "receipt does not assert source_unchanged")
    need(receipt["case_count"] == CASE_COUNT, "receipt case_count drift")
    need(receipt["deferred_count"] == DEFERRED_COUNT, "receipt deferred_count drift")
    need(receipt["julia_exit_code"] == 0, "julia child exited nonzero")
    need(receipt.get("oracle_error_count", 0) == 0, "R oracle recorded at least one computation error")
    need(set(receipt["target_source_ids"]) == set(contract["target_source_ids"]),
         "receipt target_source_ids does not match contract")

    case_ids = {x["case_id"] for x in contract["cases"]}
    seen = {}
    for line in results_lines:
        if not line.strip():
            continue
        cid, verdict, bucket = line.split("\t")
        seen[cid] = (verdict, bucket)
    need(set(seen.keys()) == case_ids, "results.tsv case_id set does not match contract cases[]")
    for cid in case_ids:
        need(seen[cid] == ("PASS", "surface_conversion"), f"{cid}: expected PASS/surface_conversion, got {seen[cid]}")

    need(julia_report["status"] == "PASS", "julia-results.json status is not PASS")
    need(julia_report["all_checks"] is True, "julia-results.json all_checks is not true")
    need(julia_report["negative_controls_behaved_as_expected"] is True,
         "julia-results.json negative controls did not behave as expected")
    need(julia_report["case_count"] == CASE_COUNT, "julia-results.json case_count drift")

    for row in contract["cases"]:
        jc = julia_report["cases"].get(row["case_id"])
        need(jc is not None, f"{row['case_id']}: missing from julia-results.json cases")
        need(jc.get("pass") is True, f"{row['case_id']}: julia-results.json reports pass=false")
        if row["kind"] == "refusal_pair":
            need(jc.get("r_raised") is True and jc.get("julia_raised") is True,
                 f"{row['case_id']}: refusal_pair case did not have both sides raise")
        elif row["kind"] == "bootstrap_structural":
            # No cross-engine numeric distance for this kind (n_boot=200
            # Monte Carlo error makes that meaningless) -- each engine's
            # own structural facts (finite/ordered/brackets_point) must be
            # present and true independently.
            r_struct = jc.get("r_structural") or {}
            jl_struct = jc.get("julia_structural") or {}
            for label, facts in (("r_structural", r_struct), ("julia_structural", jl_struct)):
                for key in ("finite", "ordered", "brackets_point"):
                    need(facts.get(key) is True,
                         f"{row['case_id']}: {label}.{key} is not true")
        else:
            need(jc.get("max_abs_diff") is not None and jc["max_abs_diff"] <= row["tolerance"],
                 f"{row['case_id']}: max_abs_diff {jc.get('max_abs_diff')} exceeds tolerance {row['tolerance']}")


def verify_state(contract, state_dir: Path):
    if not state_dir.is_dir():
        raise SystemExit(f"FATAL: --state directory does not exist: {state_dir}")
    receipt_path = state_dir / "receipt.json"
    results_path = state_dir / "results.tsv"
    julia_path = state_dir / "julia-results.json"
    for p in (receipt_path, results_path, julia_path):
        if not p.exists():
            raise SystemExit(f"FATAL: required retained-run file missing: {p}")
    receipt = json.loads(receipt_path.read_text())
    results_lines = results_path.read_text().splitlines()
    julia_report = json.loads(julia_path.read_text())
    check_state(contract, receipt, results_lines, julia_report)


# ---------------------------------------------------------------------------
# 3. --self-test: build a SYNTHETIC valid state from the contract (no R/Julia
#    needed), confirm check_state() accepts it, then mutate it >=3 ways and
#    confirm check_state() rejects every mutation.
# ---------------------------------------------------------------------------
def _synthetic_state(contract):
    cases = contract["cases"]

    results_lines = [f"{r['case_id']}\tPASS\tsurface_conversion" for r in cases]

    julia_cases = {}
    for r in cases:
        if r["kind"] == "refusal_pair":
            julia_cases[r["case_id"]] = {"pass": True, "kind": r["kind"],
                                          "r_raised": True, "julia_raised": True}
        elif r["kind"] == "bootstrap_structural":
            struct_ok = {"finite": True, "ordered": True, "brackets_point": True}
            julia_cases[r["case_id"]] = {"pass": True, "kind": r["kind"],
                                          "r_structural": dict(struct_ok), "julia_structural": dict(struct_ok),
                                          "julia_error": ""}
        else:
            julia_cases[r["case_id"]] = {"pass": True, "kind": r["kind"], "quantity": r["quantity"],
                                          "tolerance": r["tolerance"], "max_abs_diff": r["tolerance"] / 2,
                                          "r_len": 1, "julia_len": 1, "error": ""}

    julia_report = {
        "status": "PASS",
        "case_count": len(cases),
        "all_checks": True,
        "negative_controls_behaved_as_expected": True,
        "cases": julia_cases,
    }

    receipt = {
        "status": "PASS",
        "scope": "CORE070_SURFACE_CONVERSION_BATCH",
        "reference_commit": contract["reference_commit"],
        "contract_sha256": sha(CONTRACT_PATH),
        "source_unchanged": True,
        "target_source_ids": list(contract["target_source_ids"]),
        "case_count": len(cases),
        "deferred_count": len(contract["deferred"]),
        "oracle_error_count": 0,
        "julia_exit_code": 0,
    }
    return receipt, results_lines, julia_report


def run_self_test():
    contract = verify_contract()
    receipt, results_lines, julia_report = _synthetic_state(contract)

    # The synthetic state itself must be accepted -- otherwise the mutations
    # below would be "rejected" vacuously (a check that rejects everything).
    check_state(contract, receipt, results_lines, julia_report)

    rejected = []

    def expect_rejected(label, mutate_fn):
        r2, res2, jr2 = deepcopy(receipt), list(results_lines), deepcopy(julia_report)
        r2, res2, jr2 = mutate_fn(r2, res2, jr2)
        try:
            check_state(contract, r2, res2, jr2)
        except ValueError:
            rejected.append(label)
            return
        raise AssertionError(f"REJECTED MUTATION FAILED TO BE CAUGHT: {label}")

    def mut_bad_contract_sha(r, res, jr):
        r["contract_sha256"] = "0" * 64
        return r, res, jr

    def mut_flip_one_verdict(r, res, jr):
        res[0] = res[0].split("\t")[0] + "\tFAIL\tsurface_conversion"
        return r, res, jr

    def mut_tolerance_blown(r, res, jr):
        cid = next(c["case_id"] for c in contract["cases"] if c["kind"] in ("point", "ci"))
        jr["cases"][cid]["max_abs_diff"] = 1e9
        jr["cases"][cid]["pass"] = True  # deliberately inconsistent: pass=true but diff blown
        return r, res, jr

    def mut_refusal_pair_r_side_did_not_raise(r, res, jr):
        cid = next((c["case_id"] for c in contract["cases"] if c["kind"] == "refusal_pair"), None)
        if cid is None:
            raise AssertionError("contract has no refusal_pair case to mutate")
        jr["cases"][cid]["r_raised"] = False
        return r, res, jr

    def mut_bootstrap_structural_not_ordered(r, res, jr):
        cid = next((c["case_id"] for c in contract["cases"] if c["kind"] == "bootstrap_structural"), None)
        if cid is None:
            raise AssertionError("contract has no bootstrap_structural case to mutate")
        jr["cases"][cid]["julia_structural"]["ordered"] = False
        return r, res, jr

    def mut_oracle_error_present(r, res, jr):
        r["oracle_error_count"] = 1
        return r, res, jr

    expect_rejected("contract_sha256 tampered", mut_bad_contract_sha)
    expect_rejected("one verdict flipped to FAIL in results.tsv", mut_flip_one_verdict)
    expect_rejected("max_abs_diff blown past tolerance while pass stays true", mut_tolerance_blown)
    expect_rejected("refusal_pair case: R side did not raise", mut_refusal_pair_r_side_did_not_raise)
    expect_rejected("bootstrap_structural case: julia_structural.ordered flipped false", mut_bootstrap_structural_not_ordered)
    expect_rejected("receipt records a nonzero oracle_error_count", mut_oracle_error_present)

    if len(rejected) < 3:
        raise AssertionError(f"only {len(rejected)} rejected mutations ran, need >=3")

    print(f"CORE070_SURFACE_CONVERSION_VERIFY_SELF_TEST_OK rejected_mutations={len(rejected)} "
          f"cases={CASE_COUNT} deferred={DEFERRED_COUNT}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("state", nargs="?",
                     help="retained-run directory to verify (e.g. .unlazy/core070-aghq/surface-conversion-01)")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()

    if args.self_test:
        run_self_test()
        if args.state is None:
            return  # self-test alone is a valid invocation

    contract = verify_contract()
    print(f"CORE070_SURFACE_CONVERSION_CONTRACT_OK cases={CASE_COUNT} deferred={DEFERRED_COUNT} "
          f"total_target_rows={TARGET_ROW_COUNT}")

    if args.state is None:
        raise SystemExit("FATAL: no --state directory given and --self-test was not requested (or was "
                          "requested alongside a missing state) -- a self-test pass never substitutes for "
                          "a real retained-run check.")

    verify_state(contract, Path(args.state))
    print("CORE070_SURFACE_CONVERSION_STATE_OK", args.state)


if __name__ == "__main__":
    main()
