"""Verify the "namespace-1" manifest-area batch, Tier 0 (existence /
registration parity): 48 EXECUTABLE_NOW cases + 6 NEEDS_NEW_JULIA_SURFACE
deferrals; 36 REUSED_OR_RECLASSIFY rows are recorded in the contract but
deliberately carry no fabricated checks. See
docs/dev-log/core070/namespace-1-batch-contract.json for the full 90-row
manifest-freeze triage and the deferred Tier 1 numeric-fit follow-up.

Two independent checks, mirroring tools/core070_verify_postfit_policy_batch.py:

  1. verify_contract() -- structural checks on the frozen contract itself
     (bucket counts sum to the manifest's 90 rows, no case id appears in more
     than one bucket, source pins are well-formed). Needs no retained run.
  2. verify_state(path) -- structural + hash checks against a retained run of
     tools/core070_namespace_1_batch.R (receipt.json, r-facts.json,
     julia-facts.json, results.tsv, diagnostics.log).
  3. --self-test -- mutates a *synthetic* valid state (built from the frozen
     contract, no retained run required) in >=4 independent ways and asserts
     every mutation is rejected by check_state(), plus exercises the 2
     case-anchored negative controls (DEVIANCE/TIDY absence) end to end.
     Runs without R, Julia, or the frozen library. Per the postfit-policy
     precedent's vacuous-pass incident, --self-test NEVER substitutes for a
     real --state check below: passing --self-test alone still exits nonzero
     if --state does not exist.
  4. --write-case-receipts DIR -- after verifying a retained run, write one
     JSON receipt per contract row (pin, R source hashes read, Julia commit,
     both sides' facts, case and batch verdicts).

Pin: GLLVM_PARITY_PIN (read through tools/parity_oracle.py; default P0)
selects the contract. P0 checks are exactly the original ones; P1 uses
docs/dev-log/core070/true-parity-latest/namespace-1-batch-contract-p1.json
(50 executable, 2 needs-surface, 2 retired-at-P1 rows).
"""
import argparse
from copy import deepcopy
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from parity_oracle import R_REF_PINS, SELECTED_PIN  # noqa: E402  (GLLVM_PARITY_PIN switch; default P0)

# One frozen contract per pin. P0's is the original (history, unchanged); P1's
# is regenerated by tools/core070_namespace_1_p1_contract.py.
CONTRACT_PATHS = {
    "P0": ROOT / "docs/dev-log/core070/namespace-1-batch-contract.json",
    "P1": ROOT / "docs/dev-log/core070/true-parity-latest/namespace-1-batch-contract-p1.json",
}
PIN_COUNTS = {
    # executable_now, needs_new_julia_surface, retired_at_p1
    "P0": (48, 6, 0),
    "P1": (50, 2, 2),
}
if SELECTED_PIN not in CONTRACT_PATHS:
    raise SystemExit(f"no namespace-1 contract for pin {SELECTED_PIN}; regenerate one before verifying")
PIN = SELECTED_PIN
REFERENCE_COMMIT = R_REF_PINS[PIN]
CONTRACT_PATH = CONTRACT_PATHS[PIN]

MANIFEST_ROW_COUNT = 90
EXECUTABLE_NOW_COUNT, NEEDS_SURFACE_COUNT, RETIRED_COUNT = PIN_COUNTS[PIN]
REUSED_OR_RECLASSIFY_COUNT = 36


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def need(ok, message):
    if not ok:
        raise ValueError(message)


def load_contract():
    return json.loads(CONTRACT_PATH.read_text())


# ---------------------------------------------------------------------------
# 1. Contract-only structural checks (no retained run required).
# ---------------------------------------------------------------------------
def verify_contract(contract=None):
    c = contract or load_contract()
    need(c["status"] == "FROZEN_NAMESPACE_1_BATCH_CONTRACT", "wrong contract status")
    need(c["area"] == "namespace-1", "wrong area")
    need(c["reference_commit"] == REFERENCE_COMMIT, "wrong reference commit")
    need(c["manifest_row_count"] == MANIFEST_ROW_COUNT, "manifest row count drift")

    exec_ids = [x["case_id"] for x in c["cases"]]
    needs_ids = [x["case_id"] for x in c["needs_new_julia_surface"]]
    reused_source_ids = [x["source_id"] for x in c["reused_or_reclassify"]]
    retired_rows = c.get("retired_at_p1", [])
    retired_ids = [x["case_id"] for x in retired_rows]
    need(len(retired_ids) == RETIRED_COUNT, f"expected {RETIRED_COUNT} retired rows, got {len(retired_ids)}")
    for row in retired_rows:
        need(row["expected_r_registered"] is False and row["expected_r_defined"] is True,
             f"{row['case_id']}: retired row must expect unregistered + still defined")

    need(len(exec_ids) == EXECUTABLE_NOW_COUNT, f"expected {EXECUTABLE_NOW_COUNT} executable cases, got {len(exec_ids)}")
    need(len(needs_ids) == NEEDS_SURFACE_COUNT, f"expected {NEEDS_SURFACE_COUNT} needs-surface rows, got {len(needs_ids)}")
    need(len(reused_source_ids) == REUSED_OR_RECLASSIFY_COUNT,
         f"expected {REUSED_OR_RECLASSIFY_COUNT} reused/reclassify rows, got {len(reused_source_ids)}")
    need(len(c["spec_defect_notes"]) == 0, "expected 0 spec-defect rows in this batch")

    need(len(set(exec_ids)) == len(exec_ids), "duplicate case_id within cases[]")
    need(len(set(needs_ids)) == len(needs_ids), "duplicate case_id within needs_new_julia_surface[]")
    need(set(exec_ids).isdisjoint(needs_ids), "a case_id appears in both cases[] and needs_new_julia_surface[]")
    need(set(retired_ids).isdisjoint(set(exec_ids) | set(needs_ids)), "a retired case_id also appears in cases[] or needs[]")

    exec_source_ids = {x["source_id"] for x in c["cases"]}
    needs_source_ids = {x["source_id"] for x in c["needs_new_julia_surface"]}
    reused_source_id_set = set(reused_source_ids)
    need(exec_source_ids.isdisjoint(needs_source_ids), "a source_id appears in both cases[] and needs_new_julia_surface[]")
    need(exec_source_ids.isdisjoint(reused_source_id_set), "a source_id appears in both cases[] and reused_or_reclassify[]")
    need(needs_source_ids.isdisjoint(reused_source_id_set), "a source_id appears in both needs_new_julia_surface[] and reused_or_reclassify[]")

    retired_source_ids = {x["source_id"] for x in retired_rows}
    need(retired_source_ids.isdisjoint(exec_source_ids | needs_source_ids | reused_source_id_set),
         "a retired source_id also appears in another bucket")
    all_source_ids = exec_source_ids | needs_source_ids | reused_source_id_set | retired_source_ids
    need(len(all_source_ids) == MANIFEST_ROW_COUNT, f"union of all bucket source_ids is {len(all_source_ids)}, expected {MANIFEST_ROW_COUNT}")
    need(all(sid.startswith("namespace/") for sid in all_source_ids), "a source_id is missing the 'namespace/' area prefix")

    for row in c["cases"]:
        need(row["expected_julia_symbol_exists"] is True, f"{row['case_id']}: EXECUTABLE_NOW row must expect Julia symbol to exist")
        need(row["expected_r_registered"] is True and row["expected_r_defined"] is True,
             f"{row['case_id']}: EXECUTABLE_NOW row must expect R registration+definition")
    need(any(row["expected_julia_symbol_exists"] is False for row in c["needs_new_julia_surface"]),
         "expected at least one NEEDS row with a genuinely absent Julia symbol")

    for rel, digest in c["source_pins"].items():
        need(isinstance(digest, str) and len(digest) == 64, f"malformed sha256 pin for {rel}")
    need(isinstance(c["namespace_sha256"], str) and len(c["namespace_sha256"]) == 64, "malformed NAMESPACE sha256 pin")

    neg = c["negative_controls"]
    need(len(neg) >= 2, "fewer than 2 negative controls in contract")
    case_anchored_neg = [x for x in neg if x.get("case_id")]
    need(len(case_anchored_neg) >= 2, "fewer than 2 case-anchored negative controls")
    for x in case_anchored_neg:
        kind = x.get("kind", "julia_absent")
        if kind == "julia_absent":
            need(x["case_id"] in needs_ids, f"negative control {x['control_id']} does not anchor to a real needs_new_julia_surface case_id")
            row = next(r for r in c["needs_new_julia_surface"] if r["case_id"] == x["case_id"])
            need(row["expected_julia_symbol_exists"] is False, f"negative control {x['control_id']} anchors a row not expected absent")
        elif kind == "r_unregistered":
            need(x["case_id"] in retired_ids, f"negative control {x['control_id']} does not anchor to a real retired_at_p1 case_id")
        else:
            raise ValueError(f"negative control {x['control_id']}: unknown kind {kind!r}")

    return c


# ---------------------------------------------------------------------------
# 2. Retained-state checks (receipt.json + results.tsv + facts JSON).
# ---------------------------------------------------------------------------
def check_state(contract, receipt, results_lines, r_facts, julia_facts):
    need(receipt["status"] == "PASS", "receipt status is not PASS")
    need(receipt["scope"] == "CORE070_NAMESPACE_1_BATCH_TIER0", "wrong receipt scope")
    need(receipt["reference_commit"] == contract["reference_commit"], "receipt reference_commit mismatch")
    need(receipt["contract_sha256"] == sha(CONTRACT_PATH), "receipt contract_sha256 does not match the on-disk contract")
    need(receipt["executable_now_count"] == EXECUTABLE_NOW_COUNT, "receipt executable_now_count drift")
    need(receipt["needs_new_julia_surface_count"] == NEEDS_SURFACE_COUNT, "receipt needs_new_julia_surface_count drift")
    need(receipt["julia_exit_code"] == 0, "julia child exited nonzero")
    need(receipt["source_unchanged"] is True, "receipt does not assert source_unchanged")
    if PIN != "P0":
        need(receipt.get("pin") == PIN, "receipt pin does not match GLLVM_PARITY_PIN")
        need(receipt.get("retired_at_p1_count") == RETIRED_COUNT, "receipt retired_at_p1_count drift")
        jc = receipt.get("julia_commit")
        need(isinstance(jc, str) and len(jc) == 40, "receipt has no 40-hex julia_commit")
        need(receipt.get("julia_src_dirty") is False, "Julia src/ had uncommitted changes during the run")

    for rel, digest in contract["source_pins"].items():
        need(receipt["source_pins"].get(rel) == digest, f"receipt source pin for {rel} does not match contract")

    exec_ids = {x["case_id"] for x in contract["cases"]}
    needs_ids = {x["case_id"] for x in contract["needs_new_julia_surface"]}
    retired_ids = {x["case_id"] for x in contract.get("retired_at_p1", [])}

    seen = {}
    for line in results_lines:
        if not line.strip():
            continue
        cid, verdict, bucket = line.split("\t")
        seen[cid] = (verdict, bucket)

    need(set(seen.keys()) == (exec_ids | needs_ids | retired_ids), "results.tsv case_id set does not match contract exec+needs(+retired) union")
    for cid in exec_ids:
        need(seen[cid] == ("PASS", "executable_now"), f"{cid}: expected PASS/executable_now, got {seen[cid]}")
    for cid in needs_ids:
        need(seen[cid] == ("PASS", "needs_new_julia_surface"), f"{cid}: expected PASS/needs_new_julia_surface, got {seen[cid]}")
    for cid in retired_ids:
        need(seen[cid] == ("PASS", "retired_at_p1"), f"{cid}: expected PASS/retired_at_p1, got {seen[cid]}")

    r_by_case = {x["case_id"]: x for x in r_facts["facts"]} if isinstance(r_facts["facts"], list) else r_facts["facts"]
    for row in contract["cases"] + contract["needs_new_julia_surface"]:
        rf = r_by_case.get(row["case_id"])
        need(rf is not None, f"{row['case_id']}: missing from r-facts.json")
        need(rf.get("ok") is True, f"{row['case_id']}: R-side registered+defined check did not pass")

        jf = julia_facts["facts"].get(row["julia_symbol"])
        need(jf is not None, f"{row['case_id']}: julia symbol {row['julia_symbol']} missing from julia-facts.json")
        need(jf.get("exists") == row["expected_julia_symbol_exists"],
             f"{row['case_id']}: julia exists={jf.get('exists')}, expected {row['expected_julia_symbol_exists']}")

    for row in contract.get("retired_at_p1", []):
        rf = r_by_case.get(row["case_id"])
        need(rf is not None, f"{row['case_id']}: missing from r-facts.json")
        need(rf.get("registered") is False and rf.get("defined") is True and rf.get("retirement_confirmed") is True,
             f"{row['case_id']}: retirement not confirmed by the R scan")

    # Negative controls, checked against the live facts (not just the contract's
    # own recorded expectation, which verify_contract() already checked). For
    # P0 these are NEG-DEVIANCE-ABSENT and NEG-TIDY-ABSENT, exactly as before.
    for nc in contract["negative_controls"]:
        cid = nc.get("case_id")
        if not cid:
            continue
        kind = nc.get("kind", "julia_absent")
        if kind == "julia_absent":
            row = next(x for x in contract["needs_new_julia_surface"] if x["case_id"] == cid)
            need(julia_facts["facts"][row["julia_symbol"]]["exists"] is False,
                 f"{nc['control_id']}: {row['julia_symbol']} resolved as existing")
        elif kind == "r_unregistered":
            rf = r_by_case.get(cid) or {}
            need(rf.get("registered") is False and rf.get("defined") is True,
                 f"{nc['control_id']}: retired export not read as unregistered+defined")


def verify_state(contract, state_dir: Path):
    need(state_dir.is_dir(), f"--state directory does not exist: {state_dir}")
    receipt = json.loads((state_dir / "receipt.json").read_text())
    results_lines = (state_dir / "results.tsv").read_text().splitlines()
    r_facts = json.loads((state_dir / "r-facts.json").read_text())
    julia_facts = json.loads((state_dir / "julia-facts.json").read_text())
    check_state(contract, receipt, results_lines, r_facts, julia_facts)


# ---------------------------------------------------------------------------
# 3. --self-test: build a SYNTHETIC valid state from the contract (no R/Julia
#    needed), confirm check_state() accepts it, then mutate it >=4 ways and
#    confirm check_state() rejects every mutation.
# ---------------------------------------------------------------------------
def _synthetic_state(contract):
    exec_rows = contract["cases"]
    needs_rows = contract["needs_new_julia_surface"]

    r_facts_list = [
        {"case_id": r["case_id"], "source_id": r["source_id"], "registered": True, "defined": True, "ok": True}
        for r in exec_rows + needs_rows
    ]
    julia_facts = {}
    for r in exec_rows:
        julia_facts[r["julia_symbol"]] = {"exists": True}
    for r in needs_rows:
        julia_facts[r["julia_symbol"]] = {"exists": r["expected_julia_symbol_exists"]}

    retired_rows = contract.get("retired_at_p1", [])
    r_facts_list += [
        {"case_id": r["case_id"], "source_id": r["source_id"], "registered": False, "defined": True, "ok": False,
         "retirement_confirmed": True}
        for r in retired_rows
    ]
    results_lines = (
        [f"{r['case_id']}\tPASS\texecutable_now" for r in exec_rows]
        + [f"{r['case_id']}\tPASS\tneeds_new_julia_surface" for r in needs_rows]
        + [f"{r['case_id']}\tPASS\tretired_at_p1" for r in retired_rows]
    )

    receipt = {
        "status": "PASS",
        "scope": "CORE070_NAMESPACE_1_BATCH_TIER0",
        "reference_commit": contract["reference_commit"],
        "contract_sha256": sha(CONTRACT_PATH),
        "source_pins": dict(contract["source_pins"]),
        "source_unchanged": True,
        "executable_now_count": len(exec_rows),
        "needs_new_julia_surface_count": len(needs_rows),
        "julia_exit_code": 0,
    }
    if PIN != "P0":
        receipt.update({"pin": PIN, "retired_at_p1_count": len(retired_rows), "julia_commit": "0" * 40,
                        "julia_src_dirty": False})
    return receipt, results_lines, {"facts": r_facts_list}, {"facts": julia_facts}


def run_self_test():
    contract = verify_contract()
    receipt, results_lines, r_facts, julia_facts = _synthetic_state(contract)

    # The synthetic state itself must be accepted -- otherwise the mutations
    # below would be "rejected" vacuously (a check that rejects everything).
    check_state(contract, receipt, results_lines, r_facts, julia_facts)

    rejected = []

    def expect_rejected(label, mutate_fn):
        r2, res2, rf2, jf2 = deepcopy(receipt), list(results_lines), deepcopy(r_facts), deepcopy(julia_facts)
        r2, res2, rf2, jf2 = mutate_fn(r2, res2, rf2, jf2)
        try:
            check_state(contract, r2, res2, rf2, jf2)
        except ValueError:
            rejected.append(label)
            return
        raise AssertionError(f"REJECTED MUTATION FAILED TO BE CAUGHT: {label}")

    def mut_bad_contract_sha(r, res, rf, jf):
        r["contract_sha256"] = "0" * 64
        return r, res, rf, jf

    def mut_flip_one_exec_verdict(r, res, rf, jf):
        res[0] = res[0].split("\t")[0] + "\tFAIL\texecutable_now"
        return r, res, rf, jf

    absent_cid = next(x["case_id"] for x in contract["negative_controls"]
                      if x.get("case_id") and x.get("kind", "julia_absent") == "julia_absent")
    absent_sym = next(x["julia_symbol"] for x in contract["needs_new_julia_surface"] if x["case_id"] == absent_cid)

    def mut_needs_symbol_flipped_to_exist(r, res, rf, jf):
        jf["facts"][absent_sym]["exists"] = True  # an expected-absent symbol must NOT be reported as existing
        return r, res, rf, jf

    def mut_retired_read_as_registered(r, res, rf, jf):
        for x in rf["facts"]:
            if x.get("retirement_confirmed"):
                x["registered"] = True
                break
        return r, res, rf, jf

    def mut_drop_one_r_fact(r, res, rf, jf):
        rf["facts"].pop()
        return r, res, rf, jf

    def mut_source_pin_tampered(r, res, rf, jf):
        k = next(iter(r["source_pins"]))
        r["source_pins"][k] = "1" * 64
        return r, res, rf, jf

    expect_rejected("contract_sha256 tampered", mut_bad_contract_sha)
    expect_rejected("one executable_now verdict flipped to FAIL", mut_flip_one_exec_verdict)
    expect_rejected(f"{absent_sym} (expected-absent) symbol flipped to exists=true", mut_needs_symbol_flipped_to_exist)
    if contract.get("retired_at_p1"):
        expect_rejected("retired export read as registered", mut_retired_read_as_registered)
    expect_rejected("one r-facts entry dropped", mut_drop_one_r_fact)
    expect_rejected("a source pin tampered without updating the receipt", mut_source_pin_tampered)

    if len(rejected) < 4:
        raise AssertionError(f"only {len(rejected)} rejected mutations ran, need >=4")

    # Negative controls exercised end to end against the synthetic-but-valid
    # state (check_state above already enforced every case-anchored control).
    n_neg = sum(1 for x in contract["negative_controls"] if x.get("case_id"))

    print(f"CORE070_NAMESPACE_1_VERIFY_SELF_TEST_OK pin={PIN} rejected_mutations={len(rejected)} "
          f"negative_controls={n_neg} exec={EXECUTABLE_NOW_COUNT} needs={NEEDS_SURFACE_COUNT} retired={RETIRED_COUNT}")


# ---------------------------------------------------------------------------
# 4. Per-case receipts (--write-case-receipts DIR): one JSON per contract row,
#    recording what the row read, what each side reported, and the verdicts.
#    Written whether or not the batch verifies, so a failing case is recorded
#    rather than lost; main() still exits nonzero if the batch fails.
# ---------------------------------------------------------------------------
BUCKET_MEANING = {
    "executable_now": "Tier 0 existence/registration parity: the R export/S3 method is registered in the pinned "
                      "NAMESPACE and defined in the cited R file, and the named Julia symbol is defined in "
                      "GLLVModels. Not a numeric-output comparison.",
    "needs_new_julia_surface": "Tier 0 facts match the recorded NEEDS_NEW_JULIA_SURFACE expectation (R side present; "
                               "Julia surface absent or only partial). A PASS here is NOT parity: the row stays blocked.",
    "retired_at_p1": "The export left the NAMESPACE between P0 and P1 (definition still present, unexported). A PASS "
                     "confirms the retirement; the row is retired, not measured for parity.",
}


def _rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def case_verdicts(contract, results_lines, r_facts, julia_facts):
    seen = {}
    for line in results_lines:
        if line.strip():
            cid, verdict, bucket = line.split("\t")
            seen[cid] = (verdict, bucket)
    r_by_case = {x["case_id"]: x for x in r_facts["facts"]} if isinstance(r_facts["facts"], list) else r_facts["facts"]
    out = []
    for bucket, rows in (("executable_now", contract["cases"]),
                         ("needs_new_julia_surface", contract["needs_new_julia_surface"]),
                         ("retired_at_p1", contract.get("retired_at_p1", []))):
        for row in rows:
            rf = r_by_case.get(row["case_id"], {})
            r_ok = (rf.get("registered") is row["expected_r_registered"]
                    and rf.get("defined") is row["expected_r_defined"])
            if bucket == "retired_at_p1":
                jf, j_ok = None, True
            else:
                jf = julia_facts["facts"].get(row["julia_symbol"])
                j_ok = jf is not None and jf.get("exists") is row["expected_julia_symbol_exists"]
            runner = seen.get(row["case_id"])
            ok = r_ok and j_ok and runner == ("PASS", bucket)
            out.append((bucket, row, rf, jf, runner, "PASS" if ok else "FAIL"))
    return out


def write_case_receipts(contract, state_dir: Path, out_dir: Path, batch_verdict: str):
    receipt_path = state_dir / "receipt.json"
    receipt = json.loads(receipt_path.read_text())
    results_lines = (state_dir / "results.tsv").read_text().splitlines()
    r_facts = json.loads((state_dir / "r-facts.json").read_text())
    julia_facts = json.loads((state_dir / "julia-facts.json").read_text())
    if contract.get("source_access") == "git-show":
        def how(rel):
            return f"git show {contract['reference_commit']}:{rel}"
    else:
        def how(rel):
            return f"readback tree file {rel}"
    out_dir.mkdir(parents=True, exist_ok=True)
    tally = {"PASS": 0, "FAIL": 0}
    for bucket, row, rf, jf, runner, verdict in case_verdicts(contract, results_lines, r_facts, julia_facts):
        tally[verdict] += 1
        doc = {
            "schema": "core070-namespace-1-case-receipt/v1",
            "case_id": row["case_id"],
            "source_id": row["source_id"],
            "bucket": bucket,
            "meaning": BUCKET_MEANING[bucket],
            "pin": PIN,
            "reference_commit": contract["reference_commit"],
            "r_sources_read": [
                {"path": "NAMESPACE", "sha256": contract["namespace_sha256"], "read_as": how("NAMESPACE")},
                {"path": row["r_file"], "sha256": contract["source_pins"][row["r_file"]], "read_as": how(row["r_file"])},
            ],
            "r_check": {
                "namespace_line": row["r_namespace_line"],
                "definition_pattern": row["r_definition_pattern"],
                "definition_line_hint": row["r_definition_line_hint"],
                "registered": rf.get("registered"),
                "defined": rf.get("defined"),
                "expected_registered": row["expected_r_registered"],
                "expected_defined": row["expected_r_defined"],
            },
            "julia_check": None if bucket == "retired_at_p1" else {
                "symbol": row["julia_symbol"],
                "exists": None if jf is None else jf.get("exists"),
                "expected_exists": row["expected_julia_symbol_exists"],
                "note": row.get("julia_note"),
            },
            "julia_commit": receipt.get("julia_commit"),
            "julia_src_tree": receipt.get("julia_src_tree"),
            "result": runner[0] if runner else None,
            "verifier": {
                "tool": "tools/core070_verify_namespace_1_batch.py",
                "case_verdict": verdict,
                "batch_verdict": batch_verdict,
            },
            "batch_receipt": {"path": _rel(receipt_path), "sha256": sha(receipt_path)},
            "contract": {"path": _rel(CONTRACT_PATH), "sha256": sha(CONTRACT_PATH)},
        }
        (out_dir / f"{row['case_id']}.json").write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n")
    print(f"CORE070_NAMESPACE_1_CASE_RECEIPTS pin={PIN} written={sum(tally.values())} "
          f"pass={tally['PASS']} fail={tally['FAIL']} dir={_rel(out_dir)}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("state", nargs="?", help="retained-run directory to verify (e.g. .unlazy/core070-aghq/namespace-1-batch-01)")
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--write-case-receipts", metavar="DIR",
                    help="after verifying STATE, write one JSON receipt per contract row into DIR")
    args = ap.parse_args()

    if args.self_test:
        run_self_test()
        if args.state is None:
            return  # self-test alone is a valid invocation

    contract = verify_contract()
    print(f"CORE070_NAMESPACE_1_CONTRACT_OK exec={EXECUTABLE_NOW_COUNT} needs={NEEDS_SURFACE_COUNT} "
          f"reused_or_reclassify={REUSED_OR_RECLASSIFY_COUNT} total={MANIFEST_ROW_COUNT}")

    if args.state is None:
        raise SystemExit("FATAL: no --state directory given and --self-test was not requested (or was requested "
                          "alongside a missing state) -- a self-test pass never substitutes for a real retained-run check.")

    if args.write_case_receipts:
        try:
            verify_state(contract, Path(args.state))
            batch_verdict = "CORE070_NAMESPACE_1_STATE_OK"
        except ValueError as e:
            batch_verdict = f"FAILED: {e}"
        write_case_receipts(contract, Path(args.state), Path(args.write_case_receipts), batch_verdict)
        if batch_verdict != "CORE070_NAMESPACE_1_STATE_OK":
            raise SystemExit(f"FATAL: batch did not verify: {batch_verdict}")
    else:
        verify_state(contract, Path(args.state))
    print("CORE070_NAMESPACE_1_STATE_OK", args.state)


if __name__ == "__main__":
    main()
