# Retained evidence runner for the "namespace-1" manifest-area batch, Tier 0:
# existence / registration parity (48 EXECUTABLE_NOW + 6 NEEDS_NEW_JULIA_SURFACE
# cases; see docs/dev-log/core070/namespace-1-batch-contract.json for the full
# triage, including the 36 REUSED_OR_RECLASSIFY rows this batch deliberately
# does not fabricate checks for).
#
# This tier needs NO installed gllvmTMB package and NO frozen library: every
# check is a text scan of the PINNED readback R source tree (source_pins in
# the contract), confirming that each row's cited S3 method / export is both
# (a) registered in the readback NAMESPACE and (b) actually defined at the
# cited file. That is why this runner takes only a destination directory --
# unlike tools/core070_postfit_policy_batch.R, there is no <frozen-library>
# argv slot here (see the contract's runner.tier1_followup for the deferred
# numeric-fit tier that WOULD need one).
#
# argv (matches the contract's runner.outer_argv and this file's own
# --self-test, which never reaches disk under that path):
#   Rscript --vanilla tools/core070_namespace_1_batch.R <destination>
#
# Pin: GLLVM_PARITY_PIN (default: tools/parity_oracle.py's _DEFAULT_PIN, "P0")
# selects the contract and the expected commit/NAMESPACE hash from
# tools/core070_oracle_pins.toml. P0 behaves exactly as before (readback tree
# under .unlazy/). P1 reads every R byte with `git show <P1>:<path>` from the
# clone named by GLLVMTMB_DIR and handles rows retired at P1:
#   GLLVM_PARITY_PIN=P1 GLLVMTMB_DIR=<clone> Rscript --vanilla tools/core070_namespace_1_batch.R <destination>
#
# <destination> must not already exist; it is created and holds r-facts.json,
# julia-facts.json, julia-stdout.log, julia-stderr.log, results.tsv,
# diagnostics.log, and receipt.json.

args <- commandArgs(TRUE)
self_test <- length(args) == 1L && identical(args[[1]], "--self-test")

sha256_file <- function(path) {
  command <- if (nzchar(Sys.which("sha256sum"))) "sha256sum" else "shasum"
  argv <- if (identical(command, "sha256sum")) path else c("-a", "256", path)
  line <- system2(command, argv, stdout = TRUE, stderr = TRUE)
  stopifnot(is.null(attr(line, "status")), length(line) >= 1L)
  sub("[[:space:]].*$", "", line[[1L]])
}

suppressPackageStartupMessages(library(jsonlite))

root <- normalizePath(".")

# --- pin selection -----------------------------------------------------------
# GLLVM_PARITY_PIN names an entry of tools/core070_oracle_pins.toml (the shared
# pin source, D-294/D-295); unset means tools/parity_oracle.py's _DEFAULT_PIN
# (currently "P0"). Same switch and strict-on-unknown behaviour as the Python
# and Julia sides. The TOML is flat (one [Pn] table of string keys per pin), so
# a line scan suffices and no TOML package is needed.
read_pin <- function(root) {
  oracle_py <- readLines(file.path(root, "tools/parity_oracle.py"), warn = FALSE)
  default_line <- grep('^_DEFAULT_PIN\\s*=\\s*"[A-Za-z0-9_]+"', oracle_py, value = TRUE)
  stopifnot(length(default_line) == 1L)
  default_pin <- sub('^_DEFAULT_PIN\\s*=\\s*"([A-Za-z0-9_]+)".*$', "\\1", default_line)
  raw <- Sys.getenv("GLLVM_PARITY_PIN", unset = NA_character_)
  name <- if (is.na(raw)) default_pin else toupper(trimws(raw))
  lines <- readLines(file.path(root, "tools/core070_oracle_pins.toml"), warn = FALSE)
  hdr <- grep("^\\[[A-Za-z0-9_]+\\]\\s*$", lines)
  found <- sub("^\\[([A-Za-z0-9_]+)\\].*$", "\\1", lines[hdr])
  if (!name %in% found) {
    stop("GLLVM_PARITY_PIN=", raw, " is not a recognized pin. Set it to one of ",
         paste(sort(found), collapse = ", "), " (case/whitespace insensitive), or leave it unset (",
         default_pin, ").")
  }
  k <- match(name, found)
  block <- lines[(hdr[k] + 1L):(c(hdr, length(lines) + 1L)[k + 1L] - 1L)]
  field <- function(key) {
    hit <- grep(paste0("^\\s*", key, "\\s*=\\s*\""), block, value = TRUE)
    stopifnot(length(hit) == 1L)
    sub(paste0("^\\s*", key, "\\s*=\\s*\"([^\"]*)\".*$"), "\\1", hit)
  }
  list(name = name, reference_commit = field("reference_commit"),
       namespace_sha256 = field("namespace_sha256"))
}
pin <- read_pin(root)

# One frozen contract per pin. P0's is the original (history, unchanged); P1's
# is regenerated by tools/core070_namespace_1_p1_contract.py.
contract_paths <- c(
  P0 = "docs/dev-log/core070/namespace-1-batch-contract.json",
  P1 = "docs/dev-log/core070/true-parity-latest/namespace-1-batch-contract-p1.json"
)
expected_counts <- list(
  P0 = c(cases = 48L, needs = 6L, retired = 0L),
  P1 = c(cases = 50L, needs = 2L, retired = 2L)
)
if (!pin$name %in% names(contract_paths)) {
  stop("FATAL: no namespace-1 contract for pin ", pin$name, " -- regenerate one before running.")
}
contract_path <- file.path(root, contract_paths[[pin$name]])
if (!file.exists(contract_path)) {
  stop("FATAL: contract not found at ", contract_path, " -- refusing to run with no state.")
}
contract <- jsonlite::read_json(contract_path, simplifyVector = FALSE)
contract_sha256 <- sha256_file(contract_path)
retired_rows <- if (is.null(contract$retired_at_p1)) list() else contract$retired_at_p1
counts <- expected_counts[[pin$name]]

stopifnot(
  identical(contract$reference_commit, pin$reference_commit),
  identical(contract$namespace_sha256, pin$namespace_sha256),
  identical(contract$status, "FROZEN_NAMESPACE_1_BATCH_CONTRACT"),
  length(contract$cases) == contract$expected_case_count,
  contract$expected_case_count == counts[["cases"]],
  length(contract$needs_new_julia_surface) == contract$needs_new_julia_surface_count,
  contract$needs_new_julia_surface_count == counts[["needs"]],
  length(retired_rows) == counts[["retired"]],
  length(contract$negative_controls) >= 2L
)

# --- validate pinned R source (NAMESPACE + every cited file) ---------------
# P0: a pre-extracted readback tree under .unlazy/. Contracts with
# source_access = "git-show" (P1): every byte comes from
# `git -C $GLLVMTMB_DIR show <commit>:<path>` into a fresh temp dir; the
# gllvmTMB clone is never checked out or edited.
gllvmtmb_resolved <- NA_character_
if (identical(contract$source_access, "git-show")) {
  gdir <- Sys.getenv("GLLVMTMB_DIR", unset = "")
  if (!nzchar(gdir)) {
    stop("FATAL: GLLVMTMB_DIR must name a local gllvmTMB clone for pin ", pin$name,
         " (read with git show only).")
  }
  gllvmtmb_resolved <- system2("git", c("-C", shQuote(gdir), "rev-parse",
                                        shQuote(paste0(pin$reference_commit, "^{commit}"))),
                               stdout = TRUE)
  stopifnot(identical(gllvmtmb_resolved, pin$reference_commit))
  source_root <- tempfile("core070-namespace-1-src-")
  dir.create(source_root)
  for (rel in c(contract$namespace_pin, names(contract$source_pins))) {
    dest <- file.path(source_root, rel)
    dir.create(dirname(dest), recursive = TRUE, showWarnings = FALSE)
    status <- system2("git", c("-C", shQuote(gdir), "show",
                               shQuote(paste0(pin$reference_commit, ":", rel))),
                      stdout = dest)
    stopifnot(identical(status, 0L))
  }
  namespace_path <- file.path(source_root, contract$namespace_pin)
} else {
  source_root <- file.path(root, ".unlazy/core070-aghq/oracle-source/readback")
  namespace_path <- file.path(root, contract$namespace_pin)
}
stopifnot(file.exists(namespace_path))
namespace_sha_actual <- sha256_file(namespace_path)
stopifnot(identical(namespace_sha_actual, contract$namespace_sha256))
namespace_lines <- readLines(namespace_path, warn = FALSE)

for (rel in names(contract$source_pins)) {
  path <- file.path(source_root, rel)
  stopifnot(file.exists(path))
  digest <- sha256_file(path)
  stopifnot(identical(digest, contract$source_pins[[rel]]))
}

# ---------------------------------------------------------------------------
# The one check this tier performs: for one row, is the NAMESPACE line
# present verbatim, and does the cited file contain a line matching the
# row's definition regex? Exposed as a function so --self-test can call it
# directly on deliberately mutated inputs (rejected-mutation checks).
# ---------------------------------------------------------------------------
check_row <- function(row, ns_lines, file_lines) {
  registered <- row$r_namespace_line %in% trimws(ns_lines)
  defined <- any(grepl(row$r_definition_pattern, file_lines, perl = TRUE))
  list(registered = registered, defined = defined)
}

# Cache file contents once per cited file.
file_cache <- new.env(parent = emptyenv())
get_file_lines <- function(rel) {
  if (!exists(rel, envir = file_cache, inherits = FALSE)) {
    assign(rel, readLines(file.path(source_root, rel), warn = FALSE), envir = file_cache)
  }
  get(rel, envir = file_cache, inherits = FALSE)
}

all_rows <- c(contract$cases, contract$needs_new_julia_surface)

run_all_checks <- function(ns_lines, cache_fn) {
  out <- list()
  for (row in all_rows) {
    fl <- cache_fn(row$r_file)
    out[[row$case_id]] <- check_row(row, ns_lines, fl)
  }
  out
}

r_results <- run_all_checks(namespace_lines, get_file_lines)

r_facts <- lapply(all_rows, function(row) {
  res <- r_results[[row$case_id]]
  list(
    case_id = row$case_id,
    source_id = row$source_id,
    registered = res$registered,
    defined = res$defined,
    ok = isTRUE(res$registered) && isTRUE(res$defined)
  )
})
names(r_facts) <- vapply(all_rows, `[[`, "", "case_id")

# Retired rows (P1 only): exports that left the NAMESPACE between pins. The
# same scan runs; the expectation is registered = FALSE with the definition
# still present, so a PASS here CONFIRMS the retirement.
retired_results <- lapply(retired_rows, function(row) {
  res <- check_row(row, namespace_lines, get_file_lines(row$r_file))
  res$confirmed <- identical(res$registered, isTRUE(row$expected_r_registered)) &&
    identical(res$defined, isTRUE(row$expected_r_defined))
  res
})
names(retired_results) <- vapply(retired_rows, `[[`, "", "case_id")
for (row in retired_rows) {
  res <- retired_results[[row$case_id]]
  r_facts[[row$case_id]] <- list(
    case_id = row$case_id,
    source_id = row$source_id,
    registered = res$registered,
    defined = res$defined,
    ok = isTRUE(res$registered) && isTRUE(res$defined),
    retirement_confirmed = res$confirmed
  )
}

# ---------------------------------------------------------------------------
# --self-test: exercise check_row() against the real pinned sources (no
# destination dir, no Julia child) AND against >=4 deliberately mutated
# inputs to prove each check actually discriminates rather than vacuously
# passing. FAILS LOUDLY (non-zero exit via stop()) on any mismatch.
# ---------------------------------------------------------------------------
if (self_test) {
  mismatches <- character(0)
  for (row in all_rows) {
    res <- r_results[[row$case_id]]
    if (!isTRUE(res$registered) || !isTRUE(res$defined)) {
      mismatches <- c(mismatches, sprintf(
        "case %s: expected registered=TRUE defined=TRUE, got registered=%s defined=%s",
        row$case_id, res$registered, res$defined))
    }
  }

  # --- rejected mutations (>=4): corrupt inputs the check must catch -------
  rejected <- character(0)
  probe_row <- all_rows[[1]]
  probe_lines <- get_file_lines(probe_row$r_file)

  # 1. NAMESPACE line missing entirely.
  ns_without <- namespace_lines[trimws(namespace_lines) != trimws(probe_row$r_namespace_line)]
  m1 <- check_row(probe_row, ns_without, probe_lines)
  if (isTRUE(m1$registered)) stop("REJECTED MUTATION 1 FAILED TO BE CAUGHT: NAMESPACE-line removal still read as registered")
  rejected <- c(rejected, "NAMESPACE line removed -> registered=FALSE (caught)")

  # 2. Definition line removed from the source file.
  lines_without_def <- probe_lines[!grepl(probe_row$r_definition_pattern, probe_lines, perl = TRUE)]
  m2 <- check_row(probe_row, namespace_lines, lines_without_def)
  if (isTRUE(m2$defined)) stop("REJECTED MUTATION 2 FAILED TO BE CAUGHT: definition removal still read as defined")
  rejected <- c(rejected, "definition line removed -> defined=FALSE (caught)")

  # 3. NAMESPACE line present but with a typo'd class name (must NOT match).
  garbled_ns_line <- sub(",", ",ZZZ_", probe_row$r_namespace_line, fixed = FALSE)
  ns_garbled <- c(namespace_lines, garbled_ns_line)
  ns_garbled <- ns_garbled[trimws(ns_garbled) != trimws(probe_row$r_namespace_line)]
  m3 <- check_row(probe_row, ns_garbled, probe_lines)
  if (isTRUE(m3$registered)) stop("REJECTED MUTATION 3 FAILED TO BE CAUGHT: garbled NAMESPACE line still read as registered")
  rejected <- c(rejected, "garbled NAMESPACE class name -> registered=FALSE (caught)")

  # 4. Definition present under a DIFFERENT (wrong) generic name (must NOT match).
  wrong_def <- gsub(probe_row$r_name, paste0("zzz_", probe_row$r_name), probe_lines, fixed = TRUE)
  m4 <- check_row(probe_row, namespace_lines, wrong_def)
  if (isTRUE(m4$defined)) stop("REJECTED MUTATION 4 FAILED TO BE CAUGHT: renamed-generic definition still read as defined")
  rejected <- c(rejected, "definition renamed to a different generic -> defined=FALSE (caught)")

  if (length(rejected) < 4L) stop("FATAL: fewer than 4 rejected mutations ran")

  # --- negative controls (>=2): rows whose Julia symbol is genuinely absent,
  #     confirmed via the paired Julia self-test's own contract read (this R
  #     process does not load Julia; it asserts the CONTRACT records these as
  #     expected_julia_symbol_exists == FALSE, which is what the Julia
  #     self-test independently verifies against the live GLLVModels module).
  neg_case_ids <- vapply(contract$negative_controls, function(x) {
    if (is.null(x$case_id)) NA_character_ else x$case_id
  }, character(1))
  neg_case_ids <- neg_case_ids[!is.na(neg_case_ids)]
  if (length(neg_case_ids) < 2L) stop("FATAL: fewer than 2 case-anchored negative controls in contract")
  # kind "julia_absent" (the P0 contract's implicit kind): the row is a
  # NEEDS_NEW_JULIA_SURFACE row the contract records as an expected absence.
  # kind "r_unregistered" (P1): the row is a retired export and the live scan
  # must read it as unregistered but still defined.
  for (nc in contract$negative_controls) {
    cid <- nc$case_id
    if (is.null(cid)) next
    kind <- if (is.null(nc$kind)) "julia_absent" else nc$kind
    if (identical(kind, "julia_absent")) {
      row <- Filter(function(r) identical(r$case_id, cid), contract$needs_new_julia_surface)[[1]]
      if (!identical(row$expected_julia_symbol_exists, FALSE)) {
        stop("NEGATIVE CONTROL ", cid, " FAILED TO BE CAUGHT: contract does not mark it as an expected absence")
      }
    } else if (identical(kind, "r_unregistered")) {
      res <- retired_results[[cid]]
      if (is.null(res) || !identical(res$registered, FALSE) || !identical(res$defined, TRUE)) {
        stop("NEGATIVE CONTROL ", cid, " FAILED TO BE CAUGHT: retired export not read as unregistered+defined")
      }
    } else {
      stop("FATAL: unknown negative-control kind ", kind, " for ", cid)
    }
  }
  for (cid in names(retired_results)) {
    if (!isTRUE(retired_results[[cid]]$confirmed)) {
      mismatches <- c(mismatches, sprintf("retired %s: retirement not confirmed (registered=%s defined=%s)",
                                          cid, retired_results[[cid]]$registered, retired_results[[cid]]$defined))
    }
  }

  if (length(mismatches)) {
    for (m in mismatches) message("SELF_TEST_MISMATCH: ", m)
    stop("FATAL: R self-test found ", length(mismatches), " mismatch(es) on the real pinned sources -- see above.")
  }

  cat("CORE070_NAMESPACE_1_R_SELF_TEST_OK rows=", length(all_rows),
      " rejected_mutations=", length(rejected),
      " negative_controls=", length(neg_case_ids), "\n", sep = "")
  quit(status = 0L)
}

# ---------------------------------------------------------------------------
# Normal (non-self-test) invocation: write r-facts.json, invoke the Julia
# child, cross-check, write receipt.
# ---------------------------------------------------------------------------
stopifnot(length(args) == 1L)
output_dir <- args[[1]]
stopifnot(!dir.exists(output_dir))
dir.create(output_dir, recursive = TRUE)

r_facts_path <- file.path(output_dir, "r-facts.json")
jsonlite::write_json(
  list(schema = "core070-namespace-1-r-facts/v1", status = "OK", facts = r_facts),
  r_facts_path, auto_unbox = TRUE, pretty = TRUE, null = "null"
)

julia_out <- file.path(output_dir, "julia-facts.json")
julia_bin <- Sys.which("julia")
stopifnot(nzchar(julia_bin))
t0 <- Sys.time()
julia_status <- system2(julia_bin, c("--project=.", "tools/core070_namespace_1_batch.jl", shQuote(julia_out)),
                         stdout = file.path(output_dir, "julia-stdout.log"),
                         stderr = file.path(output_dir, "julia-stderr.log"),
                         env = paste0("GLLVM_PARITY_PIN=", pin$name))
elapsed <- as.numeric(Sys.time() - t0, units = "secs")

julia_report <- if (file.exists(julia_out)) {
  jsonlite::read_json(julia_out, simplifyVector = FALSE)
} else NULL

exec_ids <- vapply(contract$cases, `[[`, "", "case_id")
needs_ids <- vapply(contract$needs_new_julia_surface, `[[`, "", "case_id")

julia_ok <- function(row) {
  if (is.null(julia_report)) return(FALSE)
  f <- julia_report$facts[[row$julia_symbol]]
  !is.null(f) && identical(f$exists, row$expected_julia_symbol_exists)
}

# Contracts with julia_require_exported_callable (P1): an executable row passes only if the Julia
# symbol is exported AND a Function. isdefined alone let an unexported helper or a type count as a
# twin (review of #559). P0 keeps its original existence-only rule.
julia_exported_callable <- function(row) {
  if (!isTRUE(contract$julia_require_exported_callable)) return(TRUE)
  f <- julia_report$facts[[row$julia_symbol]]
  !is.null(f) && isTRUE(f$exported) && isTRUE(f$callable)
}

exec_pass <- vapply(contract$cases, function(row) {
  r_ok <- isTRUE(r_facts[[row$case_id]]$ok)
  r_ok && julia_ok(row) && julia_exported_callable(row)
}, logical(1))
names(exec_pass) <- exec_ids

needs_pass <- vapply(contract$needs_new_julia_surface, function(row) {
  r_ok <- isTRUE(r_facts[[row$case_id]]$ok)  # R side is still expected to be registered+defined
  r_ok && julia_ok(row)                       # and the Julia absence/partial fact must match expectation
}, logical(1))
names(needs_pass) <- needs_ids

retired_ids <- names(retired_results)
retired_pass <- vapply(retired_ids, function(id) isTRUE(retired_results[[id]]$confirmed), logical(1))

results_ok <- !is.null(julia_report) &&
  identical(julia_status, 0L) &&
  identical(julia_report$status, "OK") &&
  all(exec_pass) &&
  all(needs_pass) &&
  all(retired_pass)

raw_lines <- c(
  vapply(exec_ids, function(id) paste(id, if (isTRUE(exec_pass[[id]])) "PASS" else "FAIL", "executable_now", sep = "\t"), character(1)),
  vapply(needs_ids, function(id) paste(id, if (isTRUE(needs_pass[[id]])) "PASS" else "FAIL", "needs_new_julia_surface", sep = "\t"), character(1)),
  vapply(retired_ids, function(id) paste(id, if (isTRUE(retired_pass[[id]])) "PASS" else "FAIL", "retired_at_p1", sep = "\t"), character(1))
)
raw_path <- file.path(output_dir, "results.tsv")
writeLines(raw_lines, raw_path)

diag_lines <- character(0)
if (!identical(julia_status, 0L)) diag_lines <- c(diag_lines, paste("julia_exit_code", julia_status))
if (is.null(julia_report)) diag_lines <- c(diag_lines, "julia-facts.json was not written")
diag_path <- file.path(output_dir, "diagnostics.log")
writeLines(diag_lines, diag_path)

git_line <- function(...) {
  out <- system2("git", c("-C", shQuote(root), ...), stdout = TRUE, stderr = FALSE)
  if (length(out)) out[[1L]] else ""
}
julia_src_dirty <- length(system2("git", c("-C", shQuote(root), "status", "--porcelain", "--", "src"),
                                  stdout = TRUE, stderr = FALSE)) > 0L

receipt <- list(
  status = if (isTRUE(results_ok)) "PASS" else "FAIL",
  scope = "CORE070_NAMESPACE_1_BATCH_TIER0",
  pin = pin$name,
  reference_commit = contract$reference_commit,
  source_access = if (is.null(contract$source_access)) "readback-tree" else contract$source_access,
  gllvmtmb_commit_resolved = gllvmtmb_resolved,
  julia_commit = git_line("rev-parse", "HEAD"),
  julia_src_tree = git_line("rev-parse", "HEAD:src"),
  julia_src_dirty = julia_src_dirty,
  contract_sha256 = contract_sha256,
  namespace_sha256 = namespace_sha_actual,
  source_pins = contract$source_pins,
  source_unchanged = TRUE,
  executable_now_count = length(exec_ids),
  needs_new_julia_surface_count = length(needs_ids),
  retired_at_p1_count = length(retired_ids),
  reused_or_reclassify_count = contract$reused_or_reclassify_count,
  julia_exit_code = julia_status,
  julia_elapsed_seconds = elapsed,
  julia_facts_sha256 = if (file.exists(julia_out)) sha256_file(julia_out) else NA_character_,
  r_facts_sha256 = sha256_file(r_facts_path),
  raw_sha256 = sha256_file(raw_path),
  diagnostics_sha256 = sha256_file(diag_path),
  r_version = R.version.string
)
receipt_path <- file.path(output_dir, "receipt.json")
jsonlite::write_json(receipt, receipt_path, auto_unbox = TRUE, pretty = TRUE, null = "null")

cat("CORE070_NAMESPACE_1_BATCH_", receipt$status, "\n", sep = "")
quit(status = if (isTRUE(results_ok)) 0L else 1L)
