#!/usr/bin/env node
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { BASELINE, P1, REQUIRED, parseBoard, compareCheckpoint, provenanceProblem, rowMaps } from './true_parity_checkpoint_check.mjs';
const board = execFileSync('git',['show',`${BASELINE}:docs/dev-log/core070/true-parity-latest/scoreboard.md`],{encoding:'utf8'});
const base = parseBoard(board);
const maps = rowMaps(BASELINE);
assert.equal(maps.rows.length,317,'generated assembled map must not be counted twice');
assert.equal(new Set(maps.rows.map(r=>r.source_id)).size,317);
const candidate = () => {
  const rows = new Map([...base].map(([k,v])=>[k,{...v}]));
  for (const id of REQUIRED) rows.get(id).status = id.startsWith('family/') ? 'EVIDENCED' : 'EVIDENCED-BEHAVIOURAL';
  return rows;
};
assert.doesNotThrow(()=>compareCheckpoint(base,candidate()));
assert.throws(()=>compareCheckpoint(base,base),/required exact row/);
const wrong = candidate();
wrong.get(REQUIRED[0]).status=base.get(REQUIRED[0]).status;
const substitute=[...base].find(([k,v])=>!REQUIRED.includes(k)&&v.status==='NOT-MEASURED');
assert.ok(substitute,'baseline supplies an alternative gap');
wrong.get(substitute[0]).status='EVIDENCED';
assert.throws(()=>compareCheckpoint(base,wrong),/required exact row|unrelated status/);
const dropped=candidate();dropped.delete(substitute[0]);
assert.throws(()=>compareCheckpoint(base,dropped),/admission set/);
const changed=candidate();changed.get(REQUIRED[1]).requires='excluded';
assert.throws(()=>compareCheckpoint(base,changed),/admission or cases/);
const signed=candidate();signed.get(REQUIRED[0]).status='DISPOSITION-SIGNED';
assert.throws(()=>compareCheckpoint(base,signed),/required exact row/);
const raw='observed public refusal\n';
const read=p=>p==='raw' ? raw : JSON.stringify({reference_commit:P1});
const valid={pin:'P1',reference_commit:P1,read_from:{raw:createHash('sha256').update(raw).digest('hex')},oracle_build_receipt:'build',oracle_source_receipt:'source',evidence_kind:'r_public_bridge_boundary',verdict:'R_BOUNDARY_UNCHANGED'};
assert.equal(provenanceProblem(valid,read),null);
assert.match(provenanceProblem({...valid,reference_commit:'P0'},read),/P1/);
assert.match(provenanceProblem({...valid,read_from:{}},read),/raw hashes/);
assert.match(provenanceProblem({...valid,read_from:{raw:'0'.repeat(64)}},read),/hash mismatch/);
assert.match(provenanceProblem({...valid,verdict:'NOT_EXECUTED'},read),/bridge boundary/);
assert.match(provenanceProblem({...valid,comparison:{}},read),/bridge boundary/);
assert.match(provenanceProblem({...valid,oracle_source_receipt:undefined},read),/oracle_source/);
assert.match(provenanceProblem(valid,p=>p==='build' ? JSON.stringify({reference_commit:'P0'}) : read(p)),/oracle_build_receipt is not P1/);
console.log('P1_CHECKPOINT_CONTROLS_PASS: exact rows, unchanged contracts, P1 provenance, raw hashes and bridge context');
